### ISSUE TITLE
Why does the Employee class need a 'name' parameter for this exercise?  

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#102]
The instructions explain to include a name parameter for the Employee class but I notice a name parameter is already potentially assigned in the individual sub-classes Salaried/Hourly Employee.  Now that I'm typing this I checked your source code solution and see that Super() was used to access the name within the Employee class, but is there a reason to use Super() in this case over defining the names within sub-classes?  Thank you for your time!

**Assignment**: http://learn.rmotr.com/python/base-python-track/oop-inheritance/payroll

**User code**:
```python
class Payroll(object):
    def __init__(self, company, employee_list=[]):
        self.company = company 
        self.employee_list = employee_list
        
    def add_employee(self, employee):
        self.employee_list.append(employee)
        
    def get_annual_payroll_cost(self):
        total = 0 
        for employee in self.employee_list:
            total += employee.calculate_annual_income()
        return total 

class Employee(object):
    def __str__(self):
        return "{} makes {} annually".format(self.name, self.calculate_annual_income())

class SalariedEmployee(Employee):
    def __init__(self, name, salary):
        self.name = name 
        self.salary = salary
        
    def calculate_annual_income(self):
        return self.salary 

class HourlyEmployee(Employee):
    def __init__(self, name, hourly_wage):
        self.name = name
        self.hourly_wage = hourly_wage
        
    def calculate_annual_income(self):
        return self.hourly_wage * 40 * 52
        



```

**Comment by jsymons** [comment]
We're just getting into OOP and inheritance so we're keeping the examples fairly simple. We know that **all** employees will have a name, so it makes sense to keep that in the parent class since it's an attribute we expect every `Empolyee` and every subclass of `Employee` to have. Like I said, this is a pretty basic example, but say we wanted to do something with the `name` in the init (like ensuring it's capitalized, or doing some other form of validation)... If we define `name` in every class it means we are then going to have to make that change in every class, however if we're keeping our code DRY(**D**on't **R**epeat **Y**ourself) and just having it in the base class it means we only need to change our code in one place, this means less chance to introduce errors when modifying code.
