### ISSUE TITLE
% 2 type == int

### ISSUE THREAD

**Issue by just-Bri** [rmotr-curriculum/base-python-curriculum-questions#104]
Not sure why this doesn't work.
% 2, and if it's an int(no decimal) it's even.
Else it's odd.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/even-or-odd

**User code**:
```python
def even_or_odd(a_number):
    maths = a_number % 2
    if type(maths) == int:
        return 'even'
    else:
        return 'odd'
```

**Comment by jsymons** [comment]
`a_number % 2` is always going to be an `int` (assuming of course `a_number` is an `int` to begin with, which it is given our tests), thus your if statement is always going to be `True`. You should instead be using your `%` operator *as part of your if statement*.

**Comment by just-Bri** [comment]
I was going off what I thought int means in Python: int (signed integers) − They are often called just integers or ints, are positive or negative whole numbers with no decimal point.

Compared to float: (floating point real values) − Also called floats, they represent real numbers and are written with a decimal point dividing the integer and fractional parts.

Based on that, any even number divided 2 would be an int(a whole number like 2/4/6/13/17).
Any odd number divided by 2 would be a float(2.5, 3.5 etc).

**Comment by jsymons** [comment]
Operators depend on what you pass into them. Modulus (`%`) puts out `int` if everything you pass in is an `int`, it puts out float if you pass in float. Example: `2 % 2` is going to give `0`, an `int`, `2.0 % 2` however will give `0.0` because you passed in a float.

**Comment by just-Bri** [comment]
I understand what you're saying about input/output staying the same(int => int, float => float) but in this lesson the input is 17(an int) and I divide it by 2(% 2), the output of that that would be 8.5(not an int).

That's what I'm not understanding.

EDIT: I totally forgot % is not division, it's checking the remainder after division!
My mistake!

**Comment by santiagobasulto** [comment]
Hey @reifnotreef! In this case you're using the Modulus operator (or remainder) `%`, which is different from the "division" operator `/`. The modulus is just the "reminder" of the division performed on the number. `17 % 2` is `1`, because `16 / 2` is 0, so the reminder is `1`. In simple terms, doing `% 2` will always tell you if the number is even or odd. Even numbers are always `0` and odd numbers are always `1`: `N % 2 = X`, `X = 1` if `N` is odd, `0` otherwise. 

Aside of the modulus operator, this is a REALLY interesting topic. Speaking about division, in Python 3, if you divide `5/2` you get `2.5` as result. But in Python 2, `5 / 2` is actually `2` ("wrong" result). That's because, in Python 2, Python is not "forcing" types. If it got two integers to operate, the result will be an integer.

To have this same behavior on Python 3, you can use the `integer division` operator: `//`.

Example Python 3: https://repl.it/repls/SoupyOblongProcessor
Example Python 2: https://repl.it/repls/HungrySubtleEditor

**Comment by santiagobasulto** [comment]
btw @reifnotreef, I reopened the issue. Close it if it's clear or let me know if you need extra help.
