### ISSUE TITLE
'w' VS 'r+'

### ISSUE THREAD

**Issue by AndyDeNike** [rmotr-curriculum/base-python-curriculum-questions#110]
The cheat sheet describes that 'w' will start the writing of a file from the beginning of the file AND erase any contents of the file.  Is this the case with r+ as well (will all contents be erased?)

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/intro-to-file-management

**Comment by santiagobasulto** [comment]
No, `r+` opens the file for reading and writing, but the pointer is positioned at the beginning of the file. When you start writing to it, it just "overwrites" whatever you had written before. It's like the functionality of that annoying `insert` key in a windows PC. When every new character that you write overwrites the next one.

`w` is the only one that erases the file. That's why it's so "dangerous" and we always recommend you to check the mode.

**Comment by Jappandy** [comment]
Would "a+" append to the end of the file?
