### ISSUE TITLE
how to you interpret double? what is the double of 3?

### ISSUE THREAD

**Issue by ajakaiye33** [rmotr-curriculum/base-python-curriculum-questions#132]
I have  tried to think through this but the more I do the more confused I become

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/double-down

**User code**:
```python
def double_down(num, times_doubled):
    see_double = 1
    count = 0
    while count<times_doubled:
        see_double *= num
        count +=1
    return see_double
print(double_down(3,3))
```

**Comment by jsymons** [comment]
So 3 doubled once would be 9. Doubled twice would be 18. Essentially each time you're doubling you're multiplying by 2.

**Comment by alexzwir** [comment]
The output to loop, for your example, would be like that:

**0 time looped:** 
3,0 -> 3

**first time looped:**
3,1 -> 3*2 = 6

**second time looped:**
3,2 -> 6*2 = 12

**third time looped:**
3,3 -> 12*2 = 24

@ajakaiye33, you should multiply by 2 in your loop and use the num variable instead of creating another variable:

```
def double_down(num, times_doubled):
   counter = 0
   while counter < times_doubled:
   	num = num * 2
   	counter += 1
   return num
```
i was stuck in this exercise for a long time. lol

**Comment by santiagobasulto** [comment]
👍 @alexzwir this is really clear, thanks for the extra help.
