### ISSUE TITLE
What's wrong with this code?

### ISSUE THREAD

**Issue by marcosviv88** [rmotr-curriculum/base-python-curriculum-questions#133]
So this code seems to be working, but I get an error message. What am I doing wrong?

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/convert-pirate-to-dog

**User code**:
```python
def convert_pirate_to_dog(pirate_saying):
    for letter in pirate_saying: 
        dog_saying = letter + 'oo' 
        print(dog_saying, end="")
```

**Comment by jsymons** [comment]
So there's a couple of things going on here...
First and foremost you're using `print` instead of `return`, the tests all operate off of the **returned** value, no return statement means it returns `None`.
Because we need to use a `return` statement we need to have that *outside* the for loop, otherwise the return will break the loop on the first iteration. This means you'll need to initialize a string *outside* the for loop and concatenate it using `+=` in your for loop. You then `return` the string *after* the for loop has finished.

Hope this clears things up. If you need further explanation let me know.

**Comment by marcosviv88** [comment]
OK. Got it. Thanks Jason!. 

This is the final code:

```
def convert_pirate_to_dog(pirate_saying):
    dog_saying = ''
    for letter in pirate_saying: 
        dog_saying += letter + 'oo' 
    return dog_saying
```

Closing it.
