### ISSUE TITLE
Counting the number of iterations as years?

### ISSUE THREAD

**Issue by rruss2** [rmotr-curriculum/base-python-curriculum-questions#134]
I can't figure out how python can count how many times the while loop iterated to determine the number of years.  I think this is the approach I need to take.  If not, are there other approaches?  

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/population-growth

**User code**:
```python
def population_growth(initial_pop, annual_growth_rate, target_pop):
    counter = 1 
    result = initial_pop 
    if annual_growth_rate <= 0:
        return 'invalid growth rate'
    while target_pop < result:
        result = result * (1 + annual_growth_rate)
        counter += 1 
    return counter


```

**Comment by jsymons** [comment]
You're almost there, `counter` just needs to be initialized to 0 instead of 1, counter hear is the number of years that are needed to exceed the `target_pop`, the reason this needs to be 0 is for example if initial pop was greater than target pop, we've already reached the target pop, thus 0 years have passed, therefore we should be returning 0, your current code would instead be returning 1. As a result of this all subsequent years are **also** off by one year.
Secondly your while statement has the operator reversed, it should be `while target_pop > result` as we want to keep running the loop **until** the result has exceeded the target_pop, having it the other way around means the while loop only executes if initial_pop is greater than target_pop.

Hope this clears things up.
