### ISSUE TITLE
not sure why this code passed 

### ISSUE THREAD

**Issue by deboragaleano** [rmotr-curriculum/base-python-curriculum-questions#138]
this code passed but I don't think it actually works. Also, it's completely different from proposed solution. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/all-in-string

**User code**:
```python
def all_in_string(a_string, s1, s2, s3):
    return sum(a_string.count(x) for x in (s1, s2, s3))
```

**Comment by santiagobasulto** [comment]
This is a really smart solution @debygalser! Congrats, great use of `count()`. You're also using a generator comprehension in there! The problem with it is that `count()` will return how many times the word is present. If it's repeated, you'll count it more than once. If a word is repeated, it should only account for "1", the presence of that word. Here's an example with the code of the description, the output should be `2`, but it's `4`, because `"Python"` is repeated 3 times:

![image](https://user-images.githubusercontent.com/872296/41205901-82341d3a-6cd2-11e8-94d4-a4ba754dd0f0.png)

**Comment by santiagobasulto** [comment]
Btw, I just went ahead and added that new test, so now you can try again!

![image](https://user-images.githubusercontent.com/872296/41205929-ed26c30e-6cd2-11e8-94cf-cb169eed50e1.png)
