### ISSUE TITLE
Not understanding part of code

### ISSUE THREAD

**Issue by mattmm41286** [rmotr-curriculum/base-python-curriculum-questions#140]
I understand everything about this code except for the int_string+=str(count).  What exactly is this saying, specifically the str(count), if count=1 at the top of the code?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/string-of-numbers

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
Hey @mattmm41286! The `str` is used to match the correct types. In python, you can't mix different types, for example`int`s and `string`s. If you try doing this, it'll fail:

```python
x = 1 + 'a' 
# Error, 1 is int and 'a' is str
```

That's why we have to "force" ("cast" is the preferred word) the number to be a string before adding it to the whole thing:

```python
s = '123'  # this is a str! It has quotes surrounding it
s += 4  # this FAILS! Because s is str and 4 is int
s += str(4) # this WORKS! Because we've turned 4 into '4', a str.
```
