### ISSUE TITLE
Getting False False

### ISSUE THREAD

**Issue by mattmm41286** [rmotr-curriculum/base-python-curriculum-questions#142]
How do I change my code to get a true for the second print?  

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/is-char-in-string

**User code**:
```python
def char_in_string(a_string, char_to_look_for):
   for c in a_string:
        if c in char_to_look_for:
           return True
        else:
            return False
print(char_in_string('abcdef','X'))
print(char_in_string('abcXdef','X'))
```

**Comment by santiagobasulto** [comment]
Hey Matt! The problem with your attempt is that you're trying to return too early. The `return True` is correct, because as soon as you find the char, you can already return True. But to return False (that is, to say that the char is NOT present in the string, you must go over EVERY char in the string first. Once you've gone through ALL of them you're in position to say: "this char is not present here, I'll return False". So, you just need to make a tiny change:

```python
def char_in_string(a_string, char_to_look_for):
   for c in a_string:
        if c in char_to_look_for:
           return True
    # if we reach this point, is because the char wasn't found before
    return False
```

Makes sense?

**Comment by mattmm41286** [comment]
Yep makes sense! thanks

**Comment by santiagobasulto** [comment]
👍
