### ISSUE TITLE
Is this solution correct?

### ISSUE THREAD

**Issue by marcosviv88** [rmotr-curriculum/base-python-curriculum-questions#145]
The solution provided passes as right, but is it? when this code is ran, it only provides the position of the first char, but not the ones matching it.

Also, I'm having some trouble understanding and using the enumerate. Can you please provide some examples and explanations?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/get-positions-of-char

**User code**:
```python
def get_positions_of_char(another_string, char_being_searched_for):
    result = ''
    for pos, char in enumerate(another_string):
        if char == char_being_searched_for:
            result += str(pos) + ','
        return result
       
        
print(get_positions_of_char("XabcXdefXjahX", "X"))
```

**Comment by jsymons** [comment]
Your `return` statement should be *outside* the for loop. When python encounters a return it **immediately** returns, stopping execution of the function, this means anything past the return doesn't execute. In this case the return breaks the loop which is why you only ever get a single iteration.

`enumerate` is for when you both want to iterate over something and **keep track of the number of iterations**. So for example when iterating over a string it allows you to both get the character and the position of that character.

**Comment by marcosviv88** [comment]
I can't believe I did it again! Thanks Jason!
