### ISSUE TITLE
Prime Number test

### ISSUE THREAD

**Issue by ama4coding** [rmotr-curriculum/base-python-curriculum-questions#148]
Please help ! I set the range, but am still receiving error codes

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
def reverse_str(s):
    # Please don't change me
    return s[::-1]

# Try it on your own by uncommenting the following lines and hitting "Run Code"
print(reverse_str('abc'))
# print(reverse_str('123'))
# print(reverse_str('121'))

def is_palindromic(n):
    return str(n) == reverse_str(str(n)) 

def is_prime(n):
    if n in (2, 7919):
        return True
    if n % 2 == 0:
        return False

def next_palindromic_prime(n):
    pass
```

**Comment by santiagobasulto** [comment]
Hey Andre! First of: this is the toughest assignment of the first week, so congrats on your attempt to tackle it so early 🙌.

The problem here is your `is_prime` function. The line `if n in (2, 7919)` is not checking for a range. Is just checking if `n` is either equals to 2 or 7919.

So, for example, let's check your function for the number 19:

```python
n = 19
is n in (2, 7919)? => No! Move forward

is n % 2 == 0? => No! Move forward

FUNCTION ENDS!
```

You have to implement the `is_prime` functionality for the rest of the cases.
