### ISSUE TITLE
Multiplying stirng and then returning dictionary

### ISSUE THREAD

**Issue by ama4coding** [rmotr-curriculum/base-python-curriculum-questions#156]
I am unsure of which loop to use or how to work through this issue. Please help 

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/banana-dictionary

**User code**:
```python
def banana_dict(num):
    banana = {} 
    while num >= 1:
        new_string = banana * num
    print(new_string)
```

**Comment by jsymons** [comment]
You can use either a while or a for loop, however if you're going to use a for loop you need to be using a counter in this instance, for example:
```python
counter = 0
while counter < num:
    #do something
    counter += 1
```
The way you have it now unless `num` is less than 1 you've got an infinite loop, as since you're not changing `num` it will *always* be >= 1, so the while statement is always true, and thus it will loop forever.

If you need more clarification let me know.

**Comment by ama4coding** [comment]
Thank you Jsymons!
