### ISSUE TITLE
Passes the postiive number tests

### ISSUE THREAD

**Issue by ama4coding** [rmotr-curriculum/base-python-curriculum-questions#157]
I am unsure on how to work through negative number 

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/create-counting-list

**User code**:
```python
def create_counting_list(count_to_number):
    number_list = []
    count = 0
    if count >= 0:
        while count < count_to_number:
            count +=1
            number_list.append(count)
        return number_list
    
    else:
        return 'cannot be negative'
```

**Comment by jsymons** [comment]
The reason you're never getting your 'cannot be negative' bit to execute is this:
```python
count = 0
if count >= 0:
    ...
else:
    return 'cannot be negative'
```
So you're setting `count` to 0 and then immediately checking to see if it's >= 0, so that if statement will *always* be `True`. Instead you should be checking to see if `count_to_number` is negative, and in that case be returning `'cannot be negative'`
