### ISSUE TITLE
Getting extra answer

### ISSUE THREAD

**Issue by mattmm41286** [rmotr-curriculum/base-python-curriculum-questions#161]
when I print my code, it is giving me the correct answer and then also printing the last word and description which includes 'darn'.  Why is it excluding the first one and not the last?

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/censor-your-dictionary

**User code**:
```python
def censor_dictionary(unclean_dictionary, flagged_word):
    removal_list=[]
    for word, description in unclean_dictionary.items():
        if flagged_word in description:
            removal_list.append(word)
        for word in removal_list:
            unclean_dictionary.pop(word,None)
        return unclean_dictionary
expressions= {'pumped':'Im so darn excited!','happy':'Yeehaw','agreeable':'darn Tootin!'}
print(censor_dictionary(expressions,'darn'))
```

**Comment by jsymons** [comment]
So your `return` statement is *inside* the for loop, this causes an issue because when python encounters the `return` it **immediately** returns, breaking the loop.

However this is hiding something else that is going to cause errors...
```python3
        for word in removal_list:
            unclean_dictionary.pop(word,None)
```
You **cannot** change the size of a dictionary while iterating over it, this will cause a runtime error. Instead of modifying the original dictionary you should instead be creating a new one and populating it with the values that aren't censored.
