### ISSUE TITLE
int object is not subscriptable?

### ISSUE THREAD

**Issue by mrbaker1917** [rmotr-curriculum/base-python-curriculum-questions#165]
I am trying to do the palindromic function. I have tried the code below in IDLE, and it works, but I keep getting this error in the IDE: E TypeError: 'int' object is not subscriptable. Please help.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
def reverse_str(s):
    # Please don't change me
    return s[::-1]

# Try it on your own by uncommenting the following lines and hitting "Run Code"
# print(reverse_str('abc'))
# print(reverse_str('123'))
# print(reverse_str('121'))

def is_palindromic(n):
    x = int(reverse_str(n))
    return x == n

def is_prime(n):
    pass

def next_palindromic_prime(n):
    pass
```

**Comment by mrbaker1917** [comment]
I figured it out.

**Comment by jsymons** [comment]
So if you look at the tests they are all going to pass in integers, so when you do:
```python
    x = int(reverse_str(n))
```
You're passing `reverse_str` `n` which is an integer, while `reverse_str` assumes it's a string. You can't slice an integer, which is why you're getting that error. Somewhere you need to cast that integer as a string.
