### ISSUE TITLE
Explanation unclear :(

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/base-python-curriculum-questions#181]
This video was pretty confusing with a lot of analogies making little sense to me... The example about the bookstore between 4:20 and 6:20 especially made very little sense in regards to what constitutes a clearly defined interface, object, data, operation, etc.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-oop/intro-to-oop

**Comment by santiagobasulto** [comment]
Hey @jjk235! Sorry to hear that 😔. This lesson is a little bit abstract because we're just getting started with it. The two key takeaways from the first couple of slides, showing illustrations are:

1. we want to encapsulate the functionality of objects and we want to be "abstracted away" from it.
2. The way we'll interact with our objects is through a clearly defined interface.

Then we compare it with the bookstore example from class, which is the complete opposite, as we know the "internals" of it.

Finally, we show the whole point of OOP, which is encapsulating and combining code and data in the same "entity" (our objects).

What do you think we're missing here or how would it be more clear?

**Comment by jjk235** [comment]
Hi Santiago, thanks for the reply! I don't really understand what it means to encapsulate the functionality of objects. I don't understand what abstracted away means either. I don't understand what it means to interact with an object, or what an interface in this case would be. These are all wordings I'm very unfamiliar with and wiki page on the subject seems just as confusing to me...

**Comment by jjk235** [comment]
to someone who's already familiar with the subject these analogies and examples may almost seem self explanatory but to someone who has little knowledge on the subject, there's a lot of terms and wording being introduced without being defined

**Comment by victorbizpetrol** [comment]
I think the explanation was spot on.  OOP did not make any to me when I first saw it.  I had to embrace it and then got used to it.
