### ISSUE TITLE
Clarification on string index or string length for odd or even.

### ISSUE THREAD

**Issue by OneDevGuy** [rmotr-curriculum/base-python-curriculum-questions#183]
For the code challenge Characters in even positions. 
Even is based on string length but in Count, in even-odd positions, 
it's based on the index of the string.

I would have thought it would be on the string length.
Can I suggest adopting one for both challenges to stop confusion?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/count-in-even-odd-positions

**User code**:
```python
# Characters in even positions
paramater = 'Marvelous'
# str length 123456789
chars_in_even_positions('Marvelous') # This return avlu (string positions 2,4,6,8)

# Count in even-odd positions
phrase = 'aXbcXdXXeX'
# index   0123456789
count_in_position(phrase, 'X', 'even') # This returns 2 (index positions 4, 6)
```

**Comment by santiagobasulto** [comment]
The issue seems to be that "Characters in even positions" is starting to count from `1`, instead of `0`, right? Here's the assignment for reference: https://learn.rmotr.com/python/base-python-track/strings/characters-in-even-positions

@jasonmeeks can you check this? I think @OneDevGuy is right, we can't have inconsistencies counting from 1 instead of 0 as usual.
