### ISSUE TITLE
Why doesn't this code work for convert?

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/base-python-curriculum-questions#193]
The order of operation seems almost identical to the solution but it fails the first test. My code calculates the AUD to EUR conversion as 9.something while it should be closer to 0.6

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/currency-my-way-out

**User code**:
```python
def convert(self, target_unit):
        if self.unit is target_unit:
            return self
        else:
            self.value = round(self.value / self.USD_CONVERSIONS[self.unit] * self.USD_CONVERSIONS[target_unit],4)
            
            return self
```

**Comment by jsymons** [comment]
The issue here isn't your operation. What's causing the issue is that you're updating the value of `self` instead of returning a new `Currency` object. This is being compounded by the fact that while updating the value you don't change the `unit` to correspond to the new value. But like I said, the tests necessitate that `convert` returns a *new* `Currency` object instead of making updates in place.

**Comment by jjk235** [comment]
> The issue here isn't your operation. What's causing the issue is that you're updating the value of `self` instead of returning a new `Currency` object. This is being compounded by the fact that while updating the value you don't change the `unit` to correspond to the new value. But like I said, the tests necessitate that `convert` returns a _new_ `Currency` object instead of making updates in place.

Ah I created a big mess, huh.. Thank you for the reply!
