### ISSUE TITLE
Code Issue

### ISSUE THREAD

**Issue by yousafmufc** [rmotr-curriculum/base-python-curriculum-questions#198]
I'm not sure what's wrong with the code below. Why is 'December' test value failing?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/how-many-days-in-a-month

**User code**:
```python
def how_many_days_in(a_month):
    if a_month == 'February':
        return 28
    elif a_month == 'September' or 'April' or 'June' or 'November':
        return 30
    else:
        return 31
```

**Comment by jsymons** [comment]
The problem is that `or` doesn't work the way you're thinking it works, don't worry it's a common mistake.
```python
elif a_month == 'September' or 'April' or 'June' or 'November'
```
is the same as writing
```python
elif (a_month == 'September') or 'April' or 'June' or 'November'
```
The `'April'`, `'June'` and `'November'` all evaluate as truthy statements so elif is always `True`. The or's have to go between complete statements, the `==` doesn't carry over. To write this so that it's working along what you were thinking you would write:
```python
elif a_month == 'September' or a_month == 'April' or a_month ==' June' or a_month == 'November':
```
Or if you wanted them grouped up a cleaner way would be:
```python
elif a_month in ('September', 'April', 'June', 'November'):
```

Hope this clears things up.

**Comment by yousafmufc** [comment]
That helps a lot. Thank you.
