### ISSUE TITLE
Why is one duplicate left?

### ISSUE THREAD

**Issue by ColemanSWE** [rmotr-curriculum/base-python-curriculum-questions#217]
I wrote this code and it removes all duplicates except for the second (or ending) 1 value. Why is that? Does .count() only work from its index position?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/remove-duplicates

**User code**:
```python
def remove_duplicates(a_list):
    for i in a_list:
        if a_list.count(i) > 1:
            a_list.remove(i)
    return a_list
```

**Comment by jsymons** [comment]
What's going on here is that you're modifying a list while iterating over it, this is normally something you should avoid doing as it can cause your code to do unexpected things. Basically what happens is your `for i in a_list:` iterates until the number of completed iterations is equal to the length of `a_list`. Because you keep changing the length of `a_list` it stops iterating before you've gone over each item in the list. To see this in action run this:
```python
def remove_duplicates(a_list):
    
    for i, elem in enumerate(a_list):
        print("Iteration: {} Length: {}".format(i, len(a_list)))
        print("Selected element:")
        print("".join(str(x) for x in a_list))
        print(" "*i + '^')
        print("=================================")
        if a_list.count(elem) > 1:
            a_list.remove(elem)
    return a_list
    
remove_duplicates([1, 2, 3, 2, 1, 5, 5, 5, 3, 5, 3, 4])
```
Hope this helps.
