### ISSUE TITLE
Wondering what the difference in my code & the solution is

### ISSUE THREAD

**Issue by jjk235** [rmotr-curriculum/base-python-curriculum-questions#220]
I used .format for the variable 'limit' but the solution doesn't. It seems to be a small difference that's making my code not work and  I don't really understand why. Could you please explain why limit in this case needs to be submitted as a separate parameter?

**Assignment**: http://learn.rmotr.com/python/base-python-track/database-handling/get-best-and-worst-movies

**User code**:
```python
def get_best_and_worst_movies(db_connection, rating_type, order_dir, limit=5):
    query = 'SELECT title, {rating_type} FROM marvel ORDER BY ''{rating_type} {order_dir} LIMIT :{limit} '.format(rating_type = rating_type, limit = limit, order_dir = order_dir)
    
    cursor = db_connection.execute(query)
    return cursor.fetchall()
# Above doesn't work

def get_best_and_worst_movies(db_connection, rating_type, order_dir, limit=5):
    query = 'SELECT title, {rating_type} FROM marvel ORDER BY ''{rating_type} {order_dir} LIMIT :limit '.format(rating_type = rating_type, order_dir = order_dir)
    
    cursor = db_connection.execute(query, {'limit':limit})
    return cursor.fetchall()
#Above works
```

**Comment by jsymons** [comment]
You're going to get an SQL syntax error because say the `limit` is 5, this is what your LIMIT statement will look:
```sql
LIMIT :5
```
When it should instead be:
```sql
LIMIT 5
```
You need to get rid of the `:` before `{limit}` in your string. The colon is for when you are passing in a value via the `execute`, not for when you're using `format`

Also obligatory note that you should try to avoid using `format` to pass in parameters to SQL statements as it opens you up to SQL injection. It's always better to use the method of passing in params via the `execute`.

**Comment by jjk235** [comment]
> You're going to get an SQL syntax error because say the `limit` is 5, this is what your LIMIT statement will look:
> 
> ```sql
> LIMIT :5
> ```
> 
> When it should instead be:
> 
> ```sql
> LIMIT 5
> ```
> 
> You need to get rid of the `:` before `{limit}` in your string. The colon is for when you are passing in a value via the `execute`, not for when you're using `format`
> 
> Also obligatory note that you should try to avoid using `format` to pass in parameters to SQL statements as it opens you up to SQL injection. It's always better to use the method of passing in params via the `execute`.

Thank you. Beautifully explained answer, as always!
