### ISSUE TITLE
Why do we need a count?

### ISSUE THREAD

**Issue by spencer-porter** [rmotr-curriculum/base-python-curriculum-questions#223]
I'm looking at the provided the solution and see that you created a variable to use as a counter. Why do this instead of using the input variable 'times_doubled' like in my submitted solution? Thanks.

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/double-down

**User code**:
```python
def double_down(num, times_doubled):
    while times_doubled > 0:
        num *= 2
        times_doubled -= 1
    return num
```

**Comment by santiagobasulto** [comment]
Hey @spencer-porter! Usually we prefer not to change variables and keep "immutable" solutions. It's just a matter of preference. Specially the variables that you receive as parameters. To be honest, it's not a big deal here because `times_doubled` is a number, and won't affect other usages, but it's just more of a "design philosophy". Your code works and is a valid solution!
