### ISSUE TITLE
Boolean is failing, not sure why?

### ISSUE THREAD

**Issue by katanadxh49** [rmotr-curriculum/base-python-curriculum-questions#237]
The boolean is failing. I have tried putting it in different parts of the code and using the whole name and it's still failing. I don't know why. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/return-the-type-of-value

**User code**:
```python
def which_type(val):
    if isinstance(val, int): 
        return 'integer'
    elif isinstance(val, str):
        return 'string'
    elif isinstance(val, float): 
        return 'float'
    elif isinstance (val, bool):
        return  'boolean'
        
```

**Comment by jsymons** [comment]
So here's the thing about booleans in Python... They inherit from integers (we'll get into inheritance later), `True` and `False` are technically stored as `1` and `2` respectively. Because of this if you do `isinstance(my_bool, int)` it's going to return `True`. So if you're going to use `isinstance` to solve this you have to make sure you're checking for booleans **before** you check for ints. The other way to go about this is by checking with `type` because `type` doesn't take inheritance into account while `isinstance` does.
