### ISSUE TITLE
Why can't we use index with fp.readlines()

### ISSUE THREAD

**Issue by yousafmufc** [rmotr-curriculum/base-python-curriculum-questions#243]
Why is it not working with index of line?

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/find-line-with-string

**User code**:
```python
def which_line(filepath, a_string):
    
    with open(filepath) as fp:
        
        for line in fp.readlines():
            
            if a_string in line:
                return fp.readlines().index(line)
                
        return None
```

**Comment by jsymons** [comment]
There's a couple of issues.
The big one is that `readlines` works slightly different than you're expecting. When you first open a file you end up with a pointer in the file indicating where you are in the file, with a plain open this pointer starts at the 0 position, at the beginning of the file. After calling `readlines` the pointer moves to the end of the file upon finishing reading all the data. When you call `readlines` a second time it starts reading from the current pointer position, since the pointer is already at the end of the file there's no data to read and thus the result of `fp.readlines()` is an empty list, which is why you're getting an error.

We can fix this by moving the pointer back to the start of the file using the [seek](https://www.tutorialspoint.com/python/file_seek.htm) command before we call `readlines` the second time:
```python
if a_string in line:
    fp.seek(0)
    return fp.readlines().index(line)
```
This brings us to the second problem, we have to remember that Python is 0-indexed, this means that for example if the line we were looking for was the first line `index` would in fact return 0, so you need to increase the return value by 1:
```python
return fp.readlines().index(line) + 1
```
That being said, the way you have this you're essentially doing double the work as you're going over the list twice, once to find the line, and a second time to find its position. It would be more efficient to do both of these tasks at the same time, a feat easily accomplished via `enumerate`:
```python
for position, line in enumerate(fp.readlines()):
    if a_string in line:
        return position + 1
```
`enumerate` allows us to keep a running tally of the number of iterations the for loop has made, thus keeping track of what line number we're on. Since this is also affected by 0-indexing we again have to increase our return value by 1.
