### ISSUE TITLE
Purpose of the default line

### ISSUE THREAD

**Issue by bbookman** [rmotr-curriculum/base-python-curriculum-questions#254]
result.setdefault(key, 0) # what is the purpose of this line?  If it didn't exist, what would go wrong?

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/sum-of-dict-values

**User code**:
```python

```

**Comment by santiagobasulto** [comment]
`my_dict.setdefault` is like a regular "set key" operation, but the key is only set if there's nothing in there (a default). It's a replacement for an `if` statement:

```python
if 'some_key' not in my_dict:
    my_dict['some_key'] = 1
```

which is equivalent to this code:

```python
my_dict.setdefault('some_key', 1)
```

**Comment by bbookman** [comment]
@santiagobasulto Okay, but why is it necessary?  What would go wrong without that statement in this particular exercise?

**Comment by jsymons** [comment]
So say I have an empty dictionary:
```
my_dict = {}
```
If I then do:
```
my_dict[a_key] += 1
```
This is going to give me a key error because that key does not exist in the dictionary. But if we *first* use `setdefault`:
```
my_dict.setdefault(a_key, 0)
```
It will create that key if it isn't already there and initialize the corresponding value to 0, which will prevent a key error.
