### ISSUE TITLE
Not sure why this doesn't work...

### ISSUE THREAD

**Issue by JessLars** [rmotr-curriculum/base-python-curriculum-questions#26]
Pretty behind in class already because my new job is kicking my ass, but I'm trying to catch up. I can't figure out why this isn't working. If I set the range for is_prime to (1,n) the test for Is Not Prime passes and Is Prime fails; if I set it to (2,n) I get the opposite result. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
def reverse_str(s):
    # Please don't change me
    return s[::-1]

# Try it on your own by uncommenting the following lines and hitting "Run Code"
# print(reverse_str('abc'))
# print(reverse_str('123'))
# print(reverse_str('121'))

def is_palindromic(n):
    string_int = str(n)
    if string_int == reverse_str(string_int):
        return True
    else:
        return False


def is_prime(n):
    if n == 2:
        return True
    else:
        for i in range(2,n):
            if n > 1:
                if n % i == 0:
                    return False         
                else: 
                    return True           


def next_palindromic_prime(n):
    for i in range(2, 1000000):
        if i > n:
            if is_prime(i) == True:
                if is_palindromic(i) == True:
                    return print(i)
                    


```

**Comment by jsymons** [comment]
The problem here is that you have an else statement in your loop. So what's happening is the first number it checks against is either divisible, so not a prime, or it's not divisible and you say it's a prime.
You shouldn't be saying a number is a prime until you've checked *all* the numbers in your loop.

**Comment by santiagobasulto** [comment]
Hey @JessLars! Let's tackle it bit by bit. And don't worry cause this is a difficult assignment. As with any complex piece of code, **readability matters**. If you're able to quickly eye-scan your code, you can easily spot bugs. So, you can rewrite is_prime to something like:

```python
def is_prime(n):
    if n == 2:
        return True

    for i in range(2,n):
        if n % i == 0:
            return False

    # Important
    return True
```

First, I removed the first `else`. If your first `if` returns something, there's no need to put an `else`, cause if the first if is reached, it'll just return.
Second, the condition `if n > 1:` is kind of redundant, isn't it? Your range starts from 2, so everything is going to be greater than 1. It's not the problem, but it affects a little bit more the readability.

And finally, the real issue. You need to divide `n` by ALL the numbers between 2 and `n` in order to give a True answer. That's why I put the `return True` at the bottom.

Makes sense?

**Comment by santiagobasulto** [comment]
@JessLars was this helpful? Can I close the issue?

**Comment by JessLars** [comment]
Yes, thank you so much for the explanation. I understood the logic but
couldn’t figure out how to get the code to produce the right result. Now it
all makes sense 😊

**Comment by santiagobasulto** [comment]
Awesome 💪
