### ISSUE TITLE
How can you create one empty list of lists that you can manipulate element by element?

### ISSUE THREAD

**Issue by gitdownagain** [rmotr-curriculum/base-python-curriculum-questions#264]
I tried to create an empty list of lists with zeroes (0) and found out that I wasn't able to change one element in the sub-list without it modifying all of the sublists at the same time.  Why does Python do that?  Is there any way to solve this problem with that method?

def identity_matrix(size):
    # one list
    #one_row = [0] * size
    
    #list of lists
    #my_matrix = [one_row] * size
    my_matrix = [[0] * size] * size
    
    print(my_matrix)
    
    # fill in the values...
    
    #access a list inside a list!!!
    my_matrix[1][1] = 3 # this created a list with 3's in each sublist
    # for x in range(size):
    #     my_matrix[x][x] = 1
    #     print(x)
        
    return my_matrix
    
print(identity_matrix(3))

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/identity-matrix

**User code**:
```python

```

**Comment by jsymons** [comment]
So here's the thing, your code isn't doing what you're thinking it's doing. Your code is basically doing this:
```
l = [0] * size
my_matrix = [l] * size
```
Your matrix is basically becoming a list filled a bunch of references to the same list, not copies of the same list. So you change something in one you change it in them all.

You can work around this with a list comprehension `my_matrix = [[0] * size for x in size]` or use a for loop:
```
my_matrix = []
for i in range(size):
    my_matrix.append([0]*size)
```
The key here is that it is generating a new list each time instead of making a bunch of references to the same one.
