### ISSUE TITLE
Why does the "else" statement needs to be explicit?

### ISSUE THREAD

**Issue by Akataya** [rmotr-curriculum/base-python-curriculum-questions#275]
I tried the solution below and, while one of the tests would pass the other one would fail, until I added the "else" statement explicitly. Does it always need to be explicit when working with file management or is it due to something else?

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/write-string-to-file-optional-overwrite

**User code**:
```python
def write_string(filepath, a_string, overwrite_all=False):
    if overwrite_all:
        with open(filepath, "w") as fp:
            fp.write(a_string + "\n") 
    with open(filepath, "a") as fp:
            fp.write(a_string + "\n")
```

**Comment by jsymons** [comment]
The reason you need it explicitly here is that without it you are going to run **both** sets of open and run statements if your if statement is true. You only ever want one set to run at a time, or in other words if overwrite to run with `'w'` otherwise run with `'a'`. When you come across something where you explicitly want to do one or the other you need to explicitly put the else. The exception to this is when you want to `return` inside your different logic branches because the return stops further execution so you can get away without the explicit else. Let me know if you need further clarification.
