### ISSUE TITLE
Why do you need to use "self" to access the attributes of the class?

### ISSUE THREAD

**Issue by gitdownagain** [rmotr-curriculum/base-python-curriculum-questions#277]
I thought the method being inside the class meant it has access to class attributes inherently.  I don't usually use class attributes so I just wanted to clarify this.

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/class-and-instance-attributes

**User code**:
```python

```

**Comment by jsymons** [comment]
Assuming you're talking about class attributes and not *instance* attributes, you don's strictly need to use self, you can instead use the class name. However you can't omit some form of prefix, be it `ClassName.attribute` or `self.attribute`. The one danger here is when you're assigning values instead of just reading. If you're assigning values to class attributes you *need* to reference the class and not self, otherwise the assigned value will only be assigned at the instance level, not at the class level.
