### ISSUE TITLE
What's wrong with my code?

### ISSUE THREAD

**Issue by atmc612** [rmotr-curriculum/base-python-curriculum-questions#279]
When I test my output the results look OK... but when i try the asserts it fails. What am I doing wrong/missing in my code?

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/format-board

**User code**:
```python
# Example. Use it as a base to build your own template.
BOARD_TEMPLATE = """
O  |  O  |  X
--------------
X  |  X  |  O
--------------
O  |  X  |  O
"""


def format_tic_tac_toe_board(first_row, second_row, third_row):
    
    new_format = """
    {first_row_1}  |  {first_row_2}  |  {first_row_3}
    --------------
    {second_row_1}  |  {second_row_2}  |  {second_row_3}
    --------------
    {third_row_1}  |  {third_row_2}  |  {third_row_3}
    """.format(
        first_row_1 = first_row[0],first_row_2 = first_row[1],first_row_3 = first_row[2]
        , second_row_1 = second_row[0],second_row_2 = second_row[1],second_row_3 = second_row[2]
        , third_row_1 = third_row[0],third_row_2 = third_row[1],third_row_3 = third_row[2]
    )
    
    return new_format
 
first_row = 'XO-'
second_row = 'O--'
third_row = 'O-X'
    
print(format_tic_tac_toe_board(first_row, second_row, third_row))
```

**Comment by jsymons** [comment]
The problem here is most likely indentation related. You have your `new_format` indented to be in line with your code, this is kind of the trap of multi-line strings. The indentation of your multi line string is captured **as part of the string**, this results in the entire board being indented which will cause it to not match the unindented board that is present in the tests.
