### ISSUE TITLE
why am I failing Test Has Uppercase?

### ISSUE THREAD

**Issue by cmoore1** [rmotr-curriculum/base-python-curriculum-questions#280]
After writing this I see some very similar solutions in other in the question section however neither seem to pass the Test Has Uppercase test on this lesson. (Disclaimer: I know I could have made my if statement more efficient as a "Truthy" statement but I still use long hand *shrug*).

I get the following Assert error:

tests.py:30: in test_has_uppercase
    assert neutralize_uppercase("eXpelliarMus") == ""
E   AssertionError: assert 'eXpelliarMus' == ''
E     - eXpelliarMus

Based on my understanding of how to read this the assert statement is expecting an empty string "". However, I am 'eXpelliarMus'

I know the lesson requested a while loop but that seems inefficient with a for loop already understanding how to iterate over the input variable. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/no-uppercase-allowed

**User code**:
```python
def neutralize_uppercase(stringy):
    
    for i in stringy:
        if i == i.upper():
            return ('')
        else:
            return (stringy)
```

**Comment by jsymons** [comment]
The problem here is the else statement. What's happening is basically it's going to the first character in `stringy` and going "Is this upper case? If so, return an empty string. If it's not upper case then return stringy." This isn't what we want, we only want to return stringy *after* we've checked all the characters in stringy. Thus instead of an else statement you want the `return stringy` to happen *after* the for loop, not inside of the loop.
