### ISSUE TITLE
How do you know when to use Super instead of a regular __init__ or instance method?

### ISSUE THREAD

**Issue by gitdownagain** [rmotr-curriculum/base-python-curriculum-questions#284]
Is there any kind of general guideline or hints that tell you how to use Super?  And in this example I see that we can use Super to initialize our Hourly and Salaried employees in this example, but does that give us any additional functionality?

**Assignment**: http://learn.rmotr.com/python/base-python-track/oop-inheritance/payroll

**User code**:
```python

```

**Comment by jsymons** [comment]
You use `super` when you want to access something from the parent class *but you have something of the same name in the child class*. Quick example:
```
class Person(object):
    def __init__(self, first_name, last_name):
        self.first_name = first_name
        self.last_name = last_name

class Employee(Person):
    def __init__(self, first_name, last_name, wage):
        super().__init__(first_name, last_name)
        self.wage = wage

class Customer(Person):
    def __init__(self, first_name, last_name, loyalty_points):
        super().__init__(first_name, last_name)
        self.loyalty_points = loyalty_points
```
So every `Person` has a first and last name, both `Employee` and `Customer` also have Person functionality, so instead of rewriting the assignment stuff for first and last name, we can call the assignment in the parent class. But since our child classes also have a method called `__init__` we can't call the parent class' method directly (`self.__init__` would just point to the child class' init), thus we use `super` to access the parent class' method.
