### ISSUE TITLE
Can you explain the steps please?

### ISSUE THREAD

**Issue by SoniaBuckley** [rmotr-curriculum/base-python-curriculum-questions#285]
I do not understand the 3rd and 4th step.  What is the range function doing?  Why is it starting at 1 and adding 1 to the number? How does the num == 0 work? and how does it know that i should make it repeat banana as the key?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/banana-dictionary

**User code**:
```python
    for i in range(1, num + 1):
        bananas['banana' * i] = i
```

**Comment by jsymons** [comment]
```
for i in range(1, num + 1):
```
This is going to iterate over the numbers from 1 up to and including `num` (range goes up to but not including the second number, thus why we need to add 1 if we want to include num in the range)
```
bananas['banana' * i] = i
```
It knows that we should repeat banana as the key because `'banana' * i` is going to result in 'banana' being repeated `i` times. For example: `'abc' * 3` will produce `'abcabcabc'`

The `num == 0` works because if we do `for i in range(1, num + 1)` for `num == 0` it means `for i in range(1, 0 + 1)` which can be simplified to `for i in range(1, 1)` now remember that range goes up to *but not including* the second number. This means since we start at 1 we're already at the second number, so we end up with a zero length range, so the entire for loop gets skipped.
