### ISSUE TITLE
what is None

### ISSUE THREAD

**Issue by hina-s** [rmotr-curriculum/base-python-curriculum-questions#286]
What exactly does None do. if I remove "not longest" from the if statement, I get an error saying object of noneType has no length. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/largest-key

**User code**:
```python
def longest_key(a_dict):
    
    longest = None
    for key in a_dict:
        if not longest or len(key) > len(longest):
           longest = key
        
    return longest

d= {
    "while",
    "rmotr",
    "machine"
}    

l= longest_key(d)
print(l)
    
```

**Comment by jsymons** [comment]
None is essentially the same as the concept of null or nothing. `longest = None` means that you're saying there is no value associated with longest. You're getting that error because the `not longest` is preventing the `len(key) > len(longest)` from executing if longest is *falsey* (`None` is falsey). Without that there you end of trying to take the `len` of a None value, which you can't do because you can take the length of nothing.
