### ISSUE TITLE
class 2 question 6

### ISSUE THREAD

**Issue by yadlapallis** [rmotr-curriculum/base-python-curriculum-questions#29]
def insert_dashes(a_string):
  i = 0
  for i, find_char in enumerate(a_string):
          if i(find_char) == (i % 3 == 0):
             a_string += '-'
             i += 1
  return(a_string)   
for this int is not callable object error is coming pleas help

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/characters-in-even-positions

**User code**:
```python
def chars_in_even_positions(a_string):
   index =0
   for index,even in enumerate(a_string):
       if index(even) == (i % 2 ==0):
         return even
         index +=1
   return ''
```

**Comment by santiagobasulto** [comment]
Hello @yadlapallis can you please format your code a little bit better? Mentors will be available live tonight for help.

**Comment by jsymons** [comment]
@yadlapallis You're trying to treat `i` as if it were a function when it's an int, this is what's causing your error. Also, since you're using `enumerate` you do not need to manually update `i`, it will do that itself. Lastly, be aware that using a return *inside* your for loop will cause your for loop to break the first time it encounters the return. Once a function encounters a return, the rest of the code in the function **does not execute**. If you need more help with this I'll be hosting three hours of live mentor help tonight.
