### ISSUE TITLE
TypeError: invert_dict() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by SoniaBuckley** [rmotr-curriculum/base-python-curriculum-questions#290]
I am wondering what the error message means and how I would fix that. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/dictionary-keys-and-values

**User code**:
```python
def invert_dict():
    key = ()
    value = ()
    dict_new = {}
    for value in a_dict:
        return key == key.append(value)
    for key in a_dict:
        return value == value.append(key)
        return dict_new == {key: value}
```

**Comment by jsymons** [comment]
Your function signature currently does not take any arguments:
```
def invert_dict():
```
It should take one parameter:
```
def invert_dict(a_dict):
```
The error message is occurring because the tests try to call the function by passing in a dictionary eg: `invert_dict(my_dict)` but because your function doesn't take a parameter it throws an error when we try to give it one.
