### ISSUE TITLE
Error using customer['age']

### ISSUE THREAD

**Issue by hina-s** [rmotr-curriculum/base-python-curriculum-questions#292]
Why can't we assign eldest_customer = customer['age'] on line 9?  I understand it as the value of customer['age'] will be the eldest_customer. How can the whole customer dictionary be assigned to eldest_customer as shown in your solution. Kindly clarify.

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/eldest-customer-per-state

**User code**:
```python
def eldest_customer_per_state(customers_dict):
    result_dict = {}
    
    for state, customers in customers_dict.items():
        eldest_customer = None
        
        for customer in customers:
            if eldest_customer is None or customer['age'] > eldest_customer['age']:
               eldest_customer = customer['age]'
        result_dict[state] = eldest_customer
            
    return result_dict
    
    
```

**Comment by jsymons** [comment]
The issue here is that by doing `eldest_customer = customer['age']` you're setting `eldest_customer` to the `age` of `customer`, which is going to be an integer. This is going to break your if statement:
```python
if eldest_customer is None or customer['age'] > eldest_customer['age']:
```
because `eldest_customer` is set to an int `eldest_customer['age']` is invalid code because you're trying to pass a key or index into an integer, which you can't do. To make your if statement work your assignment of `eldest_customer` inside the `if` should instead be `eldest_customer = customer`, this causes all your code to work and your tests to pass.
