### ISSUE TITLE
Code not working with "in" condition

### ISSUE THREAD

**Issue by hina-s** [rmotr-curriculum/base-python-curriculum-questions#295]
Why isn't my code working despite checking all conditions? I've checked on line 9 and 12 if values are not None and inclusive, then append to new list.

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-functions/multi-search

**User code**:
```python
# Write your function here!
# Write your function here!
def search_animals(animals_list, given_name=None, animal_type=None):

    new_list = []
    
    for animal in animals:
        
        
        if given_name and given_name in animal['given_name']:
           new_list.append(animal)
           
        if animal_type and animal_type in animal['animal_type'] or animal_type in animal['street_name']:
           new_list.append(animal)
           
    return new_list       
           

# Please keep this list of animals here (don't change it or remove it):
animals = [
    {
        "animal_type": "Raccoon",
        "street_name": "Trash Panda",
        "given_name": "Gizmo"
    },
    {
        "animal_type": "Snake",
        "street_name": "Danger Noodle",
        "given_name": "Spaghetti"
    },
    {
        "animal_type": "Snake",
        "street_name": "Danger Noodle",
        "given_name": "Nope"
    },
    {
        "animal_type": "Penguin",
        "street_name": "Formal Chicken",
        "given_name": "Mclovin"
    },
    {
        "animal_type": "Sting ray",
        "street_name": "Sea Pancake",
        "given_name": "Flap Flap"
    },
    {
        "animal_type": "Guinea Pig",
        "street_name": "Furry Potato",
        "given_name": "Alf"
    },
    {
        "animal_type": "Platypus",
        "street_name": "Duck Puppy",
        "given_name": "Bill"
    },
    {
        "animal_type": "Seagull",
        "street_name": "Beach Chicken",
        "given_name": "Santiago"
    },
    {
        "animal_type": "Ferret",
        "street_name": "Cat Snake",
        "given_name": "Will Ferret"
    }
]
# Please keep this list of animals here
```

**Comment by jsymons** [comment]
So there's a couple of issues here...
First off you're going to get `NoneType` errors when `animal_type` isn't given with this if statement:
```python
if animal_type and animal_type in animal['animal_type'] or animal_type in animal['street_name']:
```
This is because of the or statement at the end the if statement doesn't short circuit properly on your initial `animal_type` check, in other words it doesn't matter if animal_type is `None` or not as since the or is there python will try to evaluate the part after the or. We can fix this via parentheses:
```python
if animal_type and (animal_type in animal['animal_type'] or animal_type in animal['street_name']):
```
Now that the or is within the parentheses the initial and short circuits properly and we don't actually check against stuff that's None.

The second issue is that the search is meant to be inclusive, so if they search by both given name and animal type we should return only results that match both, Your current method returns results that match either (and in fact if an item matches both it is added to the results twice). If you need help figuring out how to fix this feel free to re-open this issue.

**Comment by hina-s** [comment]
I tried it via the parantheses but just 2 test cases pass and the other two don't.  Can you please help in figuring out? Thanks.

**Comment by jsymons** [comment]
So this is the second issue I mentioned. You need to add only items that match **all** the search terms, not just one of them. For example we'll use the same data that the failing test is passing in. If we were to search using:
```python
search_animals(animals, animal_type="Snake", given_name="Nope")
```
We should only get the one result that matches both of those terms, but that's not what's happening, we are getting 4 results.
```python
if given_name and given_name in animal['given_name']:
    new_list.append(animal)
```
Is going to add one entry to the list, the "Snake" entry with `given_name`set to `Nope`, as this matches the `Nope` we pass in for `given_name`. Then after that we come to the next if statement:
```python
if animal_type and (animal_type in animal['animal_type'] or animal_type in animal['street_name']):
    new_list.append(animal)
```
This is going to add three more entries to the list, the "Snake" entry with `given_name` of `Nope`, the "Snake" entry with the `given_name` of `Spaghetti`, and the "Ferret" entry. This is because the "Snake" we pass in for `animal_type` matches the `Snake` in the `animal_type` of the two Snakes, and the `Cat Snake` `street_name` of the Ferret.

So you need to change your program logic so that it instead only matches entries that match **all** given search terms. Hopes this clears things up.

**Comment by hina-s** [comment]
Thanks!! I shall do that!
