### ISSUE TITLE
All tests failing for no.of years problem with infinite loop

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#307]
At wits end

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/population-growth

**User code**:
```python
def population_growth(initial_pop, annual_growth_rate, target_pop):
    current=initial_pop
    year=0
    while(current<target_pop):
        if(annual_growth_rate>0):
            new_pop=(current*annual_growth_rate)+current
            year+=1
        else:
            return("Invalid growth rate")
    return year
```

**Comment by jsymons** [comment]
Couple of things, you should be doing `current =` instead of `new_pop =`, and you need to look at the formula again... `Target = initial * (1 + rate) ^ (number of years)` where `^` means "to the power of" or in other words what follows the `^` is the exponent. If you need further help on this either message one of us on Slack or pop into the mentor session.
