### ISSUE TITLE
where am I going wrong- first test failing

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#314]
Thanks!

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/no-uppercase-allowed

**User code**:
```python
def neutralize_uppercase(stringy):
    i=0
   
    while i < len(stringy):
        if stringy[i].upper():
           stringy=''
           
        elif stringy[i].lower():
            i+=1 
    return stringy
            
```

**Comment by jsymons** [comment]
The problem is your if/elif statements. `upper()` and `lower()` do not check if there are upper/lower case characters in the string, they return a new string with all the characters concerted to upper or lower case respectively. Since they're returning strings unless the strings are empty it means the return values are going to evaluate as "truthy" when use in an if statement like this, therefore your first is going to always evaluate as true (unless the string is empty).
