### ISSUE TITLE
can you please help?

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#316]
pls see code

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/insert-dashes-every-3-characters

**User code**:
```python
def insert_dashes(a_string):
    i=0
    new=''
    while i<len(a_string):
        new+=a_string[i]
        if i%3==0:
            
            new+='-'
        i+=1 
            
       
       
        
    return new
```

**Comment by jsymons** [comment]
So this problem wants you to insert the dash at every third position, by starting i at 0 your dashes are going to be at the wrong position. We would want the first dash added after the character at i = 2 if we're going by zero indexing. Therefore to get things in the correct position we should start i at 1 instead of 0.
