### ISSUE TITLE
where am I going wrong?

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#321]
Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/how-many-times

**User code**:
```python
def how_many_times(a_string, a_word):
    count=0
    total=0
    
    
    if a_word in a_string:
        
        count+=1
        total+= count
    return total
```

**Comment by santiagobasulto** [comment]
What's the issue @vidsjai ?

**Comment by vidsjai** [comment]
Hi Santiago

Getting below error
tests.py:34: in test_more_than_once
    assert how_many_times(phrase, "Python") == 2
E   AssertionError: assert 1 == 2
E    +  where 1 = how_many_times('Python is a

**Comment by vidsjai** [comment]
Apologies should have been clear, first two tests pass, last test fails

**Comment by jsymons** [comment]
So the issue is that your code currently only counts up to 1 occurrence of `a_word` in `a_string`. Your if statement fires if the word is in there, then it increases the count by 1 and then you return that count. You would need to implement some complex looping code to get this to work the way you have it to count more than one time. (using split or some indexing). I would instead advise you follow the hint for this project and take a look at some of the [special string methods](https://docs.python.org/3.7/library/stdtypes.html#str.count) to help simplify things.
