### ISSUE TITLE
getting error for test repeated words. all other tests passed

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#324]
tests.py:41: in test_repeated_words
    assert all_in_string(a_string, 'Python', 'good', 'Ruby') == 2
E   AssertionError: assert 3 == 2
E    +  where 3 = all_in_string('Python is good. Python is Wise. I like Python', 'Python', 'good', 'Ruby')

test only one in string - Run Test

def test_only_one_in_string():
    assert all_in_string('abcd', 'a', 'X', 'Y') == 1
    assert all_in_string('abcd', 'X', 'a', 'Y') == 1
    assert all_in_string('abcd', 'Y', 'X', 'a') == 1

test three in string - Run Test

def test_three_in_string():
    assert all_in_string('abcd', 'a', 'b', 'c') == 3

Previous Attempts

    –

Python 3.6

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/all-in-string

**User code**:
```python
def all_in_string(a_string, s1,s2,s3):
    count=0
    a=len(a_string.split())
    
    if a >1:
        
        name=a_string.split()
        
        for i in name:
            if i in (s1,s2,s3):
                count+=1 
        return count
    else:
        for i in a_string:
            if i in (s1,s2,s3):
                count+=1
        return count
```

**Comment by jsymons** [comment]
The problem here is that if for example `a_string` contains `s1` twice it will increase the count twice. The tests expect that the count is increased once for each of the passed in strings(`s1`, `s2`, `s3`), no matter how many times the words occur, we just care that there is at least 1 occurrence. Example:
```python
all_in_string("Python is great, Python is awesome.", "Python", "great", "awesome")
```
This should return `3`. 1 because Python is in the string(doesn't matter that it's there multiple times, just so long as it's there once), 1 because great is in the string, and 1 because awesome is in the string.
