### ISSUE TITLE
Unable to get code working- have included only one word for simplicity sake

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#325]
returns index as 0 only for any  scenario

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/positions

**User code**:
```python
def positions(a_string, first_word):
    
    name=a_string.split()
   
    for first_word in name: 
        if first_word in name:
        
           return name.index(first_word) 
        
    
    else:
        index = str('-')
        return index
    
    
```

**Comment by jsymons** [comment]
Your for loop is causing this issue because `for first_word in name:` causes the `first_word` parameter that is passed in to be overwritten. You're assigning the individual words in your `name` list to `first_word` on your iterations. So first iteration `first_word` is the first item in your `name` list, and then you immediately ask if the first item(`first_word`) of your list is in your list, which assuming that list isn't empty is always going to be true. You then return the index of the first item  in your list, which is always going to be zero. Hope this clears things up.

**Comment by vidsjai** [comment]
I still do not get this. Can you please help?

**Comment by jsymons** [comment]
Ok let's break down how the code is working, we're going to step through assuming we called it the following way:
```python
positions("Did you know that Python is awesome?", "Python")
```
```python
def positions(a_string, first_word):
```
`a_string` is currently `"Did you know that Python is awesome?"` and `first_word` is currently `"Python"`
```python
    name=a_string.split()
```
So `name` is now going to be equal to `["Did", "you", "know", "that", "Python", "is", "awesome?"]`

```python
    for first_word in name:
```
This is where things start going off the rails, we are now changing the value of `first_word`, on our first iteration through the loop `first_word` is going to equal `"Did"`

```python
        if first_word in name:
```
Because we changed the value of `first_word` we are now checking if `"Did"` is in  `["Did", "you", "know", "that", "Python", "is", "awesome?"]` which is going to be `True`
```python
           return name.index(first_word) 
```
Since the if statement was `True` we then call `.index` on `name`, requesting the position of `first_word` in `name`.  This means we're asking for the position of `"Did"` in  `["Did", "you", "know", "that", "Python", "is", "awesome?"]` which is going to be `0` since it's at the first position. This situation is going to occur no matter what we input as long as `a_string` is a non-empty string. This is why your code is always returning 0.
