### ISSUE TITLE
tests are failing- unsure whats wrong

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#330]
looks like new line character issue- unable to figure

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/format-board

**User code**:
```python
# Example. Use it as a base to build your own template.
BOARD_TEMPLATE = """
O  |  O  |  X
--------------
X  |  X  |  O
--------------
O  |  X  |  O
"""


def format_tic_tac_toe_board(first_row, second_row, third_row):
        new_line='\n'
        line_1="{}   |  {}    |  {}".format(first_row[0],first_row[1],first_row[2])
        
        
        line_2="{}   |  {}    |  {}".format(second_row[0],second_row[1],second_row[2])
        
        line_3="{}   |  {}    |  {}".format(third_row[0],third_row[1],third_row[2])
        dashed_line ="_" *14
        
        return(line_1,new_line,dashed_line,new_line,line_2,dashed_line,new_line,line_3)
        
    
```

**Comment by jsymons** [comment]
Couple of things, you're missing a newline at the start and end of your return string (this is why we suggest modifying the template to use in your solution). You're also using `_` instead of `-` for your dashes. Finally `return(line_1,new_line,dashed_line,new_line,line_2,dashed_line,new_line,line_3)` is going to return a tuple, not a string, you should be doing `return x + y + z` instead of `return (x, y, z)`.
