### ISSUE TITLE
Why does index start from 2?

### ISSUE THREAD

**Issue by ghost** [rmotr-curriculum/base-python-curriculum-questions#335]
Why does index start from 2?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/subtract-reversed

**User code**:
```python
def subtract_reversed(a_list):
    if len(a_list) == 0:
        return 0

    result = a_list[-1]
    index = 2
    while index <= len(a_list):
        elem = a_list[-1 * index]
        result -= elem
        index += 1

    return result
```

**Comment by jsymons** [comment]
So I'm assuming you pulled this from the solution, the reason index is starting at 2 is because inside our for loop we're doing `elem = a_list[-1 * index]` which is going to give us a negative number for the index we're accessing, which in turn is going to mean we're accessing the elements in reverse order (-1 would mean last element, -2 second last, etc.). This is because we're trying to subtract the elements in reversed order, So for example if we call `subtract_reversed([1, 2, 3])` it would set result to 3(`a_list[-1]`) and then subtract 2 and then 1, giving us a final result of 0, which is what we would expect giving the project parameters.
