### ISSUE TITLE
Why can't I use enumerate here?

### ISSUE THREAD

**Issue by ghost** [rmotr-curriculum/base-python-curriculum-questions#336]
Like in the example code?

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/get-search-match-indexes

**User code**:
```python
def get_search_match_indexes(list_being_frisked, search_term):
    list = []
    
    for index, elem in enumerate(list_being_frisked):
        if elem == search_term:
            list += index 
            
    return list
```

**Comment by jsymons** [comment]
The error message you're getting isn't concerning enumerate, it's concerning this line:
```python
list += index
```
You can't add a list and an integer like that, you can only add other iterables to lists (ie. other lists, strings, tuples, etc.) because the add operation when applied to a list tries to iterate over the other object and `append` all its elements to the list. What you're actually looking to do is:
```python
list.append(index)
```
Which will add index as a new element to the list.
