### ISSUE TITLE
Can't the range function start with 0 instead of 1?

### ISSUE THREAD

**Issue by ghost** [rmotr-curriculum/base-python-curriculum-questions#344]
Can't the range function here start with 0 instead of 1 and just go to 'num'?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/banana-dictionary

**User code**:
```python
def banana_dict(num):
    bananas = {}
    for i in range(1, num + 1):
        bananas['banana' * i] = i
    return bananas
```

**Comment by jsymons** [comment]
This would require modifying the code inside the loop to accommodate that change:
```python
for i in range(0, num):
        bananas['banana' * i + 1] = i + 1
```
Otherwise we would only go up to but not including num (range always goes up to but but including). Also i = 0 would give us `bananas['banana' * 0] = 0` which would simplify to `bananas[0] = 0` which is not something we want.
