### ISSUE TITLE
Test failing only against Test with No items

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#348]
tests.py:36: in test_with_no_items
    assert longest_key({}) == None
E   AssertionError: assert '' == None
E    +  where '' = longest_key({})

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/largest-key

**User code**:
```python
def longest_key(a_dict):
    new=''
    
    for i in a_dict.keys():
        
        if len(i)>len(new):
            new+=i
        if len(i)==0:
            return None
    return new
        
        
        
```

**Comment by jsymons** [comment]
So if we read the test that's failing:
```python
def test_with_no_items():
    assert longest_key({}) == None
```
And then look at our error message:
```
tests.py:36: in test_with_no_items
assert longest_key({}) == None
E AssertionError: assert '' == None
E + where '' = longest_key({})
```
We can tell by the `assert` statement that if we pass our function in an empty dictionary the test expects it to return `None` however according to our error message (`AssertionError: assert '' == None`) we are instead returning an empty string. The code you have for returning None currently is for if you encounter a zero length key, not an empty dictionary. Because the dictionary is empty you can't iterate over it and it just skips over your for loop.
