### ISSUE TITLE
totally lost with the second function

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#354]
Can you pls help as to where I'm going wrong?

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/analyze-string

**User code**:
```python
def count_words(a_string):
    new_list={}
    m=a_string.split(" ")
    for i in m:
        new_list.setdefault(i,0)
        new_list[i] +=1 
    return new_list
    

def get_list_of_duplicates(word_count_dict):
    oldfn=count_words(new_list)
    
    b=sorted(oldfn.keys())
    return b
    
```

**Comment by santiagobasulto** [comment]
Hello @vidsjai! I think you're having the right approach, but... **PLEASE NAME YOUR VARIABLES BETTER!**; it's really hard to interpret the code with these names. What about something like `words = a_string.split(); for word in words`, etc.

Please paste the code with better variable names and we can keep improving it here. I'll leave this issue open.

**Comment by vidsjai** [comment]
Sorry Santiago.Here you go.

def count_words(a_string):
    new_list={}
    words=a_string.split(" ")
    for word in words:
        new_list.setdefault(word,0)
        new_list[word] +=1 
    return new_list
    

def get_list_of_duplicates(word_count_dict):
    oldfn=count_words(new_list)
    
    final_list=sorted(oldfn.keys())
    return final_list

**Comment by jsymons** [comment]
Part of the issue here is scoping, `get_list_of_duplicates` has no idea what `new_list` is, that's from within the scope of `count_words` and doesn't exist outside that function. You should be operating off `word_count_dict` which is what we're passing in as a parameter. Secondly your code seems to be only sorting a list, when what we're expecting is to have a list returned that contains the words that have a count higher than 1. Also as an aside, `new_list` is really not a good variable name for a **dictionary**, it's super important to use good variable names as it will make your code easier to understand, not just for others but for yourself as well. As programmers we aren't always writing new code from scratch, we're frequently working with existing code bases and the easier code is to understand and read, the easier it is to maintain.
