### ISSUE TITLE
Unsure about the middle lines

### ISSUE THREAD

**Issue by vidsjai** [rmotr-curriculum/base-python-curriculum-questions#362]
I do know something is wrong with the for loop for width. At the moment I'm returning None.Can you please help?Thanks

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/create-empty-box

**User code**:
```python
def create_empty_box(height, width, char):
    box=''
    if len(height)>3 or len(width)>3:
        
    
        for box_height in range(height):
            for box_width in range(0,width,1):
                box+=char
            box+='\n'
        return box
    else:
        return 'Invalid box dimensions'
```

**Comment by jsymons** [comment]
A few things going on here. First off your code is erroring out at:
```python
if len(height)>3 or len(width)>3:
```
This is because you can't take then `len` of an `int`, both `height` and `width` are integers.

As for your loop...
```python
for box_width in range(0,width,1):
```
is doing the exact same thing as if you used:
```python
for box_width in range(width):
```
`range` works like this: `range([start=0], stop, [step=1]) such that start is where the range starts (this defaults to 0 if not given), stop is where it stops(exclusively, this means that `stop` is not part of the `range`), and finally `step` is what the number is increased by each time (this defaults to 1 if not given)

What i often suggest to people struggling with this problem is to first write your code such that it can construct the "inner box" (the empty space if it were filled with a character instead of empty space), once you have that you can instead of the character fill if with `' '`, a string containing a single space. This now forms the empty box. Then all you have to do create the border around it, which is just a string of `char*width` for the top and bottom borders, and then you just need to add a `char` to the beginning and ending of each line made by your "inner box" code.
