### ISSUE TITLE
Using or statement - run time very long

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#365]
In the below code in I use an or statement in the next_palindromic_prime function, I get a very long runtime. Any way to make this more efficient?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
def reverse_str(s):
    # Please don't change me
    return s[::-1]

# Try it on your own by uncommenting the following lines and hitting "Run Code"
# print(reverse_str('abc'))
# print(reverse_str('123'))
# print(reverse_str('121'))

def is_palindromic(n):
    str(n)
    if str(n)==reverse_str(str(n)):
        return True
    else:
        return False

def is_prime(n):
    if n > 0:
        if n==2 or n==3:
            return True
        elif n==1:
            return False
        else:
            for i in range(2,n):
                if n%i==0:
                    return False
            return True
                
def next_palindromic_prime(n):
    n+=1
    x = is_palindromic(n)
    y = is_prime(n)
    while (x!=True or y!=True) :
        n+=1
    return n
```

**Comment by jsymons** [comment]
So here's the thing, because you're doing:
```python
x = is_palindromic(n)
y = is_prime(n)
```
It's messing up your while loop.
```python
while (x != True or y != True):
```
Is evaluating what they were *before* your for loop. Those evaluations don't occur each loop. It just stays static. You should instead not store those in variables and just put them in your while loop:
```python
while is_palindromic(n) != True or is_prime(n) != True:
```
This causes those functions to trigger **every** iteration of the loop.
This can also be cleaned up further:
```python
while not is_palindromic(n) or not is_prime(n):
```

**Comment by gmrkss** [comment]
awesome, thank you!
