### ISSUE TITLE
Different code than suggested solution

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#370]
Hi, my code was different than the suggested solution (included below) and was wondering how the suggested solution actually works. I ran it in Python Tutor and couldn't follow why it worked. It almost appeared to skip looping through each letter entirely. 

Could you explain why?

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/no-uppercase-allowed

**User code**:
```python
def neutralize_uppercase(stringy):
    count = 0
    while count < len(stringy):
        if stringy[count] == stringy[count].upper():
            stringy = ""
            break
        count += 1
    return stringy
```

**Comment by santiagobasulto** [comment]
Hello @gmrkss! Can you add your solution? We can't see it here.

**Comment by martinzugnoni** [comment]
Hi @gmrkss, depending on the "stringy" you send to the function the `while` iteration might finish in the very first loop, because of the `break` statement you can see in your code. That makes total sense, because even in the first letter is uppercase, you will return an empty string and it doesn't make sense to keep looking through all other letters.

Hope it helps.
