### ISSUE TITLE
Order of if functions

### ISSUE THREAD

**Issue by msingh060** [rmotr-curriculum/base-python-curriculum-questions#383]
I originally had the "M > Max" before the "Max is None" test and it didn't work. Can you explain why? I would think that since Max is already defined as None if any entry is made into a_string it pass the first test and move down to redefine Max, and if nothing is entered Max would remain None / an empty string. I had some trouble writing the return line (line 6) - Max (the variable) is either the max character or still None so why the need to have to options for a return, and how does Python now which one to return - Variable Max or ""?

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/max-character

**User code**:
```python
def max_char(a_string):
    Max = None
    for M in a_string:
        if Max is None or M > Max:
            Max = M
    return Max or ""
    
None == ""
```

**Comment by santiagobasulto** [comment]
Python3 is very "strict" when comparing things of different types. For example, `3 > 'a'` will raise an error, because it doesn't make sense to compare numbers and strings ("like comparing apples to oranges").

So, the first check is a "safety one", let's make sure that Max isn't None, so we can compare it to the current string. That will be run only for the first character run.

Also: name variables all in lowercase, in a couple of weeks you guys will see OOP, and uppercase are “reserved” for classes.

**Comment by jsymons** [comment]
Just to add to this, ordering in conditionals can be important:
```python
expression_a or expression_b
```
`expression_b` will get evaluated **only** if `expression_a` evaluated as `False`. This is why your if worked when ordered one way and not the other. `Max is None` handles the case when we don't have a value associated, and then `M > Max` (which as @santiagobasulto explained will throw an error if `Max` is `None`) will evaluate all other cases.
