### ISSUE TITLE
30:19 of above video

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#391]
How does the result[cat] = result.get(cat,0) + 1 line work?

Can you explain the interpretation?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/nested-collections

**Comment by jsymons** [comment]
`result[cat] = result.get(cat,0) + 1`
First let's go over how `.get` works, if I call `my_dict.get(my_key, default_value)` it's going to try and retrieve the value associated with the `my_key` key in `my_dict` (or in other words `my_dict[my_key]`), if it exists everything is cool and it gives us that value. However if it doesn't exist it is instead going to give us `default_value`. So if we look at the code again:
```python
result[cat] = result.get(cat, 0) + 1
```
We're setting `result[cat]` to whatever it's current value is + 1 if it exists, otherwise we set it to 0 + 1. Or in other words we're incrementing the value at `result[cat]` and setting it to 1 if it doesn't exist.
