### ISSUE TITLE
descending steps

### ISSUE THREAD

**Issue by msingh060** [rmotr-curriculum/base-python-curriculum-questions#394]
Can you explain where I'm going wrong here with my descending steps? If I start at range height + 1, stop at 1, and step down by  -1 each round of the loop I thought I could get there.

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-3/advanced-nested-pyramids

**User code**:
```python
def advanced_nested_pyramid(height, char, order):
    result = ''
    if order == "ASC":
        level = ''
        for step in range(1, height + 1):
            for c in range(step):
                level += char
            level += '\n'
        result += level
    
    else:
        level = ''
        for step in range(height + 1, 1, -1):
            for c in range(step):
                level += char
            level += '\n'
        result += level
    
    return result
                
```

**Comment by jsymons** [comment]
You want `range(height, 0, -1)` instead of `range(height + 1, 1, -1)`. Using the latter means if `height` is `7` your range will go from `height + 1` (`8`) to `2`, because range goes up to but not including the stop value. This will result in the top level of the pyramid being 8 characters wide and the bottom level being 2 characters wide when we instead want the top to be `height` (7 in this case) characters wide and the bottom to be 1 character wide. We get the correct values if we use `range(height, 0, -1)` as this range when given a `height` of `7` will go from 7 to 1.

**Comment by msingh060** [comment]
that was helpful thanks!
