### ISSUE TITLE
What's wrong with my for loop?

### ISSUE THREAD

**Issue by branhoff** [rmotr-curriculum/base-python-curriculum-questions#40]
I know I'm just misunderstanding something but I'm not sure what is needed. How can I tell my loop to add 'oo' to every character in the string?

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/convert-pirate-to-dog

**User code**:
```python

```

**Comment by jsymons** [comment]
You essentially need to build a new string by iterating over the characters of the old string abs adding them asking with your additional characters to your new string. You need to build a new string because strings are immutable and thus can't be altered.

**Comment by branhoff** [comment]
def convert_pirate_to_dog(pirate_saying):
    dog_saying = pirate_saying
    for char in dog_saying:
        dog_saying = char + 'oo'
    return dog_saying
    pass

print(convert_pirate_to_dog('abcdef'))

so in this case when I print my solution I keep getting 'foo' the last character + 'oo'.

**Comment by jsymons** [comment]
It really helps to format your code properly to hello us debug so we can see the indentation you're using See https://guides.github.com/features/mastering-markdown/ for details

Your `dog_saying` should start as an empty string for starters, secondly inside your for loop you should be using `dog_saying +=` instead of `dog_saying =`. The latter will *replace* the string while the former will essentially append to it.

**Comment by santiagobasulto** [comment]
@branhoff did this work? Please close the issue if it's resolved or let us know if you need extra help.
