### ISSUE TITLE
Why does this bring an assertion error?

### ISSUE THREAD

**Issue by wiseelephant** [rmotr-curriculum/base-python-curriculum-questions#412]
Hello! I tried the code below and passed the 'red' and 'blue' tests for Magenta but failed the Orange and Green tests. I looked over the solution and saw that the if statements are bundled together. I am not sure why the code I wrote is not valid. Any explanation of why I'm wrong / why the solution is correct would be appreciated. Looking forward to learning more about this. Thanks!

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/color-mixer

**User code**:
```python
def color_mixer(color1, color2):
    if color1 == 'red' or 'blue' and color2 == 'red' or 'blue':
        return 'Magenta'
    elif color1 == 'blue' or 'yellow' and color2 == 'blue' or 'yellow':
        return 'Green'
    elif color1 == 'yellow' or 'red' and color2 == 'yellow' or 'red':
        return 'Orange'
```

**Comment by jsymons** [comment]
Or statements don't work the way that it looks like you think they work...
```python
if color1 == 'red' or 'blue' and color2 == 'red' or 'blue':
```
The above is functionally equivalent to:
```python
if (color1 == 'red') or ('blue') and (color2 == 'red') or ('blue'):
```
The or does not operate such that you can say that color1 is either red or blue. What it's saying is if color1 is 'red' or True, because 'blue' is a truthy value being a non zero length string. To accomplish what you want you would want to write something like `color1 in ('red', 'blue')` or `(color1 == 'red' or color1 == 'blue')` note the parentheses on the second one as you want to couple those statements.

**Comment by wiseelephant** [comment]
I see! Thank you for clarifying!

**Comment by ramrajkonuganti** [comment]
Can you tell me what did I do wrong here?

def color_mixer(color1, color2):
    if color1 == ('red' or 'blue') and color2 == ('blue' or 'red'):
        return 'Magneta'
    elif color1 == ('blue' or 'yellow') and color2 == ('yellow' or 'blue'):
        return 'Green'
    elif color1 == ('yellow' or 'red') and color2 == ('red' or 'yellow'):
        return 'Orange'
    else:
        pass

**Comment by ramrajkonuganti** [comment]
Never mind. You already answered my question above :)
