### ISSUE TITLE
a_string[1::2]

### ISSUE THREAD

**Issue by zli715** [rmotr-curriculum/base-python-curriculum-questions#419]
Can you explain the logic behind the a_string[1::2] solution? Same with the reverse string, I don't quite understand what the meaning of two colons in the bracket means.

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/characters-in-even-positions

**User code**:
```python
def chars_in_even_positions(a_string):
    count = 1 
    output = ''
    for c in a_string:
        if count%2 == 0:
            output += c
        count += 1
    return output
```

**Comment by jsymons** [comment]
So `a_string[1::2]` is utilizing string slicing, the way that works is basically `my_string[start:stop:step]` where `start` indicates what character to start at (or the first one if omitted), `stop` indicates what character to stop before (or just continue to the end if ommitted), and `step` indicates how many positions to move each time. So knowing that if we look at `a_string[1::2]` our `start` is one, or the second character (because in python things start at 0 not 1), we haven't supplied a `stop` so it will continue all the way to the end, and our `step` is 2, so each time we move 2 positions before we grab the next character. As a result that particular slice is going to grab characters in even positions.
