### ISSUE TITLE
How to check efficiency of the solution?

### ISSUE THREAD

**Issue by okurtphed** [rmotr-curriculum/base-python-curriculum-questions#423]
I ended up with different solution as I am not very familiar with suggested setdefault method. 

Is this a good solution or just too many iterations?

How can I test or evaluate the efficiency of the solution if I have no other solutions to compare?

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/sum-of-dict-values

**User code**:
```python
def sum_of_dict_values(d1, d2, d3):
    sum_dic = {}
    for dic in (d1, d2, d3):
        for key, value in dic.items():
            if key not in sum_dic:
                sum_dic[key] = value
            else: 
                if type(sum_dic[key]) != type(value):
                    sum_dic[key] = None
                else:
                    sum_dic[key] += value
    return sum_dic
    

```

**Comment by jsymons** [comment]
You could do this without needing to use the outer for loop because we know the keys to all be the same:
```python
def sum_of_dict_values(d1, d2, d3):
    result = {}
    for key in d1:
        if type(d1[key]) == int and \
           type(d2[key]) == int and \
           type(d3[key]) == int:
               result[key] = sum((d1[key], d2[key], d3[key]))
        else:
            result[key] = None
    return result
```
This only requires a one loop through the keys where yours has to loop through the keys three times (once for each dict).

Defining how efficient something is however is a discussion that is going to involve talking about how complex an algorithm is, which is generally defined via [Big O Notation](https://en.wikipedia.org/wiki/Big_O_notation) which is a bit outside the scope of the course.
