### ISSUE TITLE
Why doesn't concatenation or setting the variable equal to itself with the .append function work?

### ISSUE THREAD

**Issue by roccocervantes** [rmotr-curriculum/base-python-curriculum-questions#425]
Before I figured out the final solution, I tried the below two solutions. I'm inclined to think this should work, but it didn't pass the assert statements.

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-1/append-to-list

**User code**:
```python
#Option 1:
def append_to_list(hungry_list, data):
    hungry_list = hungry_list.append(data)
    return hungry_list

#Option 2:
def append_to_list(hungry_list, data):
    hungry_list += data 
    return hungry_list


```

**Comment by santiagobasulto** [comment]
Hey @roccocervantes! This is a GREAT question:


### Option 1
In this case the problem is that the `.append` method **does NOT** return the list: **It returns None!**. That means that you've just set `hungry_list` to `None` and you're basically returning that. You can actually see that on the test, it tells that it returns None:

![image](https://user-images.githubusercontent.com/872296/56162710-1188d980-5fa3-11e9-9fd8-3e74836be477.png)

The correct solution would be:

```python
#Option 1:
def append_to_list(hungry_list, data):
    hungry_list.append(data)
    return hungry_list
```

### Option 2

The problem in this case is that the `+=` method adds "a collection" to another collection. As `data` is a string, it's treating it as "a collection" of characters and separating them individually.

![image](https://user-images.githubusercontent.com/872296/56162781-2cf3e480-5fa3-11e9-8df0-b0202a6559ac.png)

The trick is to enclose `data` in a list, making it a 1-element list with only that element. The correct solution would be:

```python
#Option 1:
def append_to_list(hungry_list, data):
    hungry_list += [data]
    return hungry_list
```
