### ISSUE TITLE
I'm getting a E   TypeError: 'int' object is not iterable error

### ISSUE THREAD

**Issue by roccocervantes** [rmotr-curriculum/base-python-curriculum-questions#427]
Not too sure why, but I'm getting a TypeError: E   TypeError: 'int' object is not iterable

I tried to use the dict() function in line 2, but it doesn't seem to help. This feels like a pretty basic for loop, so not really sure where I'm going wrong.

Thanks,
Rocco

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/dictionary-keys-and-values

**User code**:
```python
def invert_dict(old_dict):
    old_dict = dict(old_dict)
    final = {}
    for key, value in old_dict:
        new_key = value 
        new_value = key 
        final[new_key] = new_value
    return final 
```

**Comment by jsymons** [comment]
If you're trying to get the keys and values out of `old_dict` you need to use `old_dict.items()`. If you don't specify `.items()` you're just going to get the keys. So if you have
```python
a_dict  = {1: 'a'}
```
and try to 
```python
for key, value in a_dict:
```
What's going to happen is it's going to try to unpack the keys as if they were an iterable and place the values into your `key` and `value` variables, however since `1` isn't an iterable you get the error you're receiving. So instead just do:
```python
for key, value in a_list.items()
```
Then things should work out as your expecting. Also, there's no need for the `old_dict = dict(old_dict)` as we're only reading from it and then storing the new data in a separate dictionary.
