### ISSUE TITLE
best practices

### ISSUE THREAD

**Issue by msingh060** [rmotr-curriculum/base-python-curriculum-questions#429]
is it best practice to pass the super() function arguments from the parent class or to leave empty like in the solution. Not sure I entirely understand how to read it when arguments are passed, but when blank I am reading as I can use any methods defined in the parent class in the subclass - is that correct?

**Assignment**: http://learn.rmotr.com/python/base-python-track/oop-inheritance/cow-says-moo

**User code**:
```python
class Animal(object):
    def __init__(self, name):
        self.name = name
        
    def talk(self):
        return '{name} says {sound}'.format(name = self.name, sound = self.sound)

class Cow(Animal):
    def __init__(self, name):
        self.sound = 'moo'
        super().__init__(name)

class Sheep(Animal):
    def __init__(self, name):
        self.sound = 'baaaaa'
        super().__init__(name)

class Fox(Animal):
    def __init__(self, name):
        self.sound = 'Ring-ding-ding-ding-dingeringeding'
        super().__init__(name)
```

**Comment by jsymons** [comment]
I'm assuming you're talking about say in your `Cow` class using `super().__init__(name)` vs `super(Cow, self).__init__(name)`. The difference is that the `super(Cow, self)` version will work in python 2.x while the simplified one will not. With python 2.7 reaching end of life at the end of the year making code cross-compatible is less important, but if you could potentially be in a 2.x environment it's important to be aware of what needs to be done to make code cross-compatible.

If you were instead wondering why we're passing name to the super it's because the parent class's `__init__` expects to receive that parameter. When we do `super().__init__(name)` we are basically calling `__init__` from our parent class.
