### ISSUE TITLE
KeyError: 'add'

### ISSUE THREAD

**Issue by gmrkss** [rmotr-curriculum/base-python-curriculum-questions#432]
Hi, having an issue adding a new key value pair to the empty cache dictionary, getting the error in line 11 below. Any ideas?

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-oop/cached-calculator

**User code**:
```python
class Calculator(object):
    # def __init__(self, x, y):
    #     self.x = x
    #     self.y = y
    cache={
        # 'add':[],
        # 'subtract':[]
    }
    
    def add_to_cache(self, function, data, output):
        if self.cache[function]:
            self.cache[function].append(data, output)
        else:
            self.cache[function]=list(data, output)
                
    def add(self, x, y):
        self.add_to_cache('add', [x, y], x+y)
        return x+y
    
    def subtract(self, x, y):
        return x-y

    
c = Calculator()
b= c.add(2, 3)

print(c.cache)
```

**Comment by jsymons** [comment]
Your if statement should read `if function in self.cache:` instead of `if self.cache[function]:`, the latter only checks if the value associated with the key `function` is truthy, not if the key is in the dictionary. This is why you're getting a `KeyError` as it's trying to access the value associated with a key that isn't present.
