### ISSUE TITLE
Having a hard time testing for primes

### ISSUE THREAD

**Issue by Deiberk** [rmotr-curriculum/base-python-curriculum-questions#436]
it looks like my code returns True (that the number is prime) when it should be False for numbers divisible by something other than 2 

for i in range(2,n):
        if (n % i) == 0:
            return False 
            break
        else:
            return True 

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/palindromic-primes

**User code**:
```python
def reverse_str(s):
    # Please don't change me
    return s[::-1]

# Try it on your own by uncommenting the following lines and hitting "Run Code"
# print(reverse_str('abc'))
# print(reverse_str('123'))
# print(reverse_str('121'))

def is_palindromic(n):
    n = str(n)
    if (n) == (n[::-1]):
        return True 
    else:
        return False
        
def is_prime(n):
    for i in range(2,n):
        if (n % i) == 0:
            return False 
            break
        else:
            return True 

def next_palindromic_prime(n):
    print (n)
```

**Comment by jsymons** [comment]
So here's what's going on, say `n` is `3`...
```python
if (3 % 2) == 0:
    return False
```
So that if statement isn't true so we move onto the else statement...
```python
else:
    return True
```
And here's our problem. We're returning True here. Remember, when a return is encountered execution of the function **immediately** stops and and the function returns. This means it breaks out of loops. So as a result of that else: return True your function will always only do one iteration of the for loop, it's either an even number and returns False, or it returns True. What you should instead be doing is only returning True *after* the for loop has completely finished:
```python
for i in range(2, n):
    if n % i == 0:
        return False
return True
```
Note how the indentation of the `return True` places it **outside** of the for loop, so it only is reached once the for loop has completely finished iterating.
