### ISSUE TITLE
How does the code " for in a_string" know to check for the string?

### ISSUE THREAD

**Issue by Vtran4** [rmotr-curriculum/base-python-curriculum-questions#441]
I finish the problem using a while loop.  I am a bit confused how the for loops know to check for string character without any actual coding of it.

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/is-char-in-string

**User code**:
```python
def char_in_string(a_string, char_to_look_for):
    for char in a_string:
        if char_to_look_for == char:
            return True
            
    return False
```

**Comment by jsymons** [comment]
So with strings and for loops it iterates over the characters in the string. So each loop through it sets `char` to the next character. This might help visualize it better for you, this is similar to what's happening:
```python
i = 0
while i < len(a_string):
    char = a_string[I]
    i += 1
```
However with a for loop Python handles the iterating for you instead of you having to manually do it like you do with a while loop.
