### ISSUE TITLE
Assert error - my board isn't matching the expected

### ISSUE THREAD

**Issue by Deiberk** [rmotr-curriculum/base-python-curriculum-questions#442]
I can't see all the lines in the assertion error.  I've copied the final_boars format provided but seem to be getting an error.  I think I have my board formated correctly without extra white spaces, so I'm not sure why I'm getting the error. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/format-board

**User code**:
```python
def format_tic_tac_toe_board(first_row, second_row, third_row):
    a = first_row[0]
    b = first_row[1]
    c = first_row[2]
    d = second_row[0]
    e = second_row[1]
    f = second_row[2]
    g = third_row[0]
    h = third_row[1]
    i = third_row[2]
    board = """
    {}  |  {}  |  {}
    --------------
    {}  |  {}  |  {}
    --------------
    {}  |  {}  |  {}
    """
    
   # print (board.format(a, b, c, d, e, f, g, h, i))
    return board.format(a, b, c, d, e, f, g, h, i)
```

**Comment by jsymons** [comment]
The problem here is that you've indented your multilinear string. When using multiline strings **everything** between the `"""` becomes part of the string, including all the whitespace from indentation. If you unindent all the lines of the multiline string except the first one it should fix the issue.
