### ISSUE TITLE
Need help with my code

### ISSUE THREAD

**Issue by ramrajkonuganti** [rmotr-curriculum/base-python-curriculum-questions#443]
Assignment/Quiz URL: https://learn.rmotr.com/python/base-python-track/week-1-quiz/all-in-string#!

Please let me know what's wrong with my code.

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/all-in-string

**User code**:
```python
def all_in_string(a_string, s1, s2, s3):
    x = all_in_string.count( "s1,  s2, s3")
    if ('s1' and 's2' and 's3') in x==0:
        return '0'
    else:
        return x
```

**Comment by jsymons** [comment]
So you can't call `count` on your function, you need to call it on a string.

For example:
```python
my_string = "Python is great!"
count = my_string.count("Python")
```
Is going to result in  `count` having a value of `1` because `"Python"` occurs once in `my_string`. However that being said we aren't asking for counts here, just if the substrings are present. This can be accomplished by doing checks like `if s1 in a_string` which is simpler than having to check against counts.
