### ISSUE TITLE
A more efficient way

### ISSUE THREAD

**Issue by nicktlc** [rmotr-curriculum/base-python-curriculum-questions#444]
Hi

I was able to pass both test but I'm just wondering if there's a better way to do this or writing a more efficient code

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/insert-dashes-every-3-characters

**User code**:
```python
def insert_dashes(a_string):
    y = ""
    x = ""
    for c in a_string:
        x += c
        if len(x)==3:
            x += "-"
            y += x
            x = ""
    return y + x
    
```

**Comment by jsymons** [comment]
You could combine the use of enumerate and the modulus operator to trigger inserting the dash every third iteration:
```python
def insert_dashes(a_string):
    result = ''
    for i, char in enumerate(a_string):
        result += char
        if (i+1) % 3 == 0:
            result += '-'
    return result
```
`enumerate` supplies us with the number of the iteration we're on (which we are assigning to `i`) so first iteration `i` will equal `0`, second iteration `i` will equal 1, and so on. The modulus operator returns the remainder of division, so the first iteration the if statement becomes `if (0+1) % 3 == 0)` since 3 does not divide into 1 evenly, the result will not be 0, we will only get a result of zero every third iteration.
