### ISSUE TITLE
A more efficient way

### ISSUE THREAD

**Issue by nicktlc** [rmotr-curriculum/base-python-curriculum-questions#445]
passed the tests but just wondering if there's a more efficient way or another method to do this?

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/characters-in-even-positions

**User code**:
```python
def chars_in_even_positions(a_string):
    even_counter = len(a_string)/2
    counter = 1
    final = ""
    while counter <= even_counter:
        final += a_string[2*counter-1]
        counter += 1
    return final
```

**Comment by jsymons** [comment]
```python
def chars_in_even_positions(a_string):
    result = ""
    for i in range(1, len(a_string), 2):
        result += a_string[i]
    return result
```
So range can take three parameters: *start*, *stop*, and *step*. *Start* indicates what number to start at, *stop* indicates which number to stop before, and *step* indicates what to increase the number by each time. So by doing `range(1, len(a_string), 2)` we are generating numbers from 1 to but not including the length of `a_string`, and we are only generating every other number. Since Python is 0 indexed, this effectively gives us all the even position indexes within `a_string`.
