### ISSUE TITLE
How to understand the difference between str and repr

### ISSUE THREAD

**Issue by roccocervantes** [rmotr-curriculum/base-python-curriculum-questions#448]
I'm having trouble understanding the use cases for the str and repr magic methods. In the lectures, the main distinction was that the str magic method is primarily for end user outputs, while the repr magic method is used to debug code and used among developers. However, I don't understand why when printing a list we use repr, but when printing just an object, we use the str method. 

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/horse-representation

**User code**:
```python

```

**Comment by jsymons** [comment]
So the reason it's going to use repr with the list is because we're calling string on the list, not the Horse object. Thus it prints out the list, and the way converting a list to a string is that it generates a string representation of the list and all its contents, now when dealing with the contents it's concerned about the *representation of the object* **not** the user readable version of that object, meaning that the `str(horse_party` is essentially doing `"[" + ", ".join(repr(horse) for horse in horse_party" + "]".
