### ISSUE TITLE
Can I reverse the list first?

### ISSUE THREAD

**Issue by MoodyG** [rmotr-curriculum/base-python-curriculum-questions#451]
I wanted to reverse the list before looping and then go with addition in stead of subtraction.  Not sure why my code is not working for many elements.  Typeerror:  'int' object is not iterable.

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-control-flow/subtract-reversed

**User code**:
```python
def subtract_reversed(a_list):
    index = 0
    result = a_list[:: -1]
    if len(a_list) == 0: 
        return 0 
    while index <= len(a_list):
        numbers = a_list[index]
        result += numbers
        
        index += 1
    return result

**Comment by jsymons** [comment]
You shouldn't be storing your reversed list in result but in another variable. The error you're getting is because you're trying to add `result` (which is your reversed list) and `numbers` which is going to be an integer from `a_list`. This is why you're getting an error as you can only add another iterable to a list.
