### ISSUE TITLE
Why wouldnt dict() work here and i notice the solution uses the string.ascii_lowercase, can I use line.lower() here? 

### ISSUE THREAD

**Issue by jojoms711** [rmotr-curriculum/base-python-curriculum-questions#458]
def counter_by_letter(filepath):
    result = dict()

    with open(filepath) as fp:
        for line in fp.readlines():
            line = line.lower()

            result[line[0]] += 1
        return result

**Assignment**: http://learn.rmotr.com/python/base-python-track/file-management/count-lines-starting-with-each-letter

**User code**:
```python

```

**Comment by jsymons** [comment]
The problem isn't `dict()`, it's that you're trying to use += on keys that aren't in the dictionary. Remember `my_dict[key] += value` expands to `my_dict[key] = my_dict[key] + value`, if that key isn't in the dictionary you're going to get a key error. Since the tests expect 0s for any letter that doesn't have a corresponding line you need to pre-initialize the dictionary with keys corresponding to all the letters of the alphabet and a value of 0 so your `+=` functions properly.

As for your other question, `line.lower()` is fine.

**Comment by jojoms711** [comment]
thank you!
