### ISSUE TITLE
Why doesn't this work?

### ISSUE THREAD

**Issue by roccocervantes** [rmotr-curriculum/base-python-curriculum-questions#461]
I built one dictionary with both the query and the limit, with the idea of using the dictionary to build the .execute() statement. However, I get an error when I run this code. I took a look at the solution, and I am inclined to believe these solutions are equivalent. Where have I gone wrong?

**Assignment**: http://learn.rmotr.com/python/base-python-track/database-handling/get-movies-and-directors

**User code**:
```python
def get_movies_and_directors(db_connection, limit=5):
    query_dict = {}
    query_dict["query"] = "SELECT m.title, m.director FROM marvel m LIMIT :limit"
    query_dict["limit"] = limit
    cursor = db_connection.execute(query_dict["query"], query_dict["limit"])
    return cursor.fetchall()
```

**Comment by jsymons** [comment]
You're slightly off on how to use parameterized SQL statements, this should instead look like:
```python
sql = "SELECT m.title, m.director FROM marvel m LIMIT :limit"
params = {'limit': limit}
cursor = db_connection.execute(sql, params)
return cursor.fetchall()
```
The first parameter to `execute` should just be a string containing your SQL, the second parameter should be a dictionary with key:value pairs where the keys match your variables in your sql, so in this example because we have the variable `:limit` we need a key of `'limit'` in our dictionary. The execute will then replace the variables in the sql with the values associated with the corresponding keys.
