### ISSUE TITLE
Need more explanation on the getattr method in search method.

### ISSUE THREAD

**Issue by vchau76** [rmotr-curriculum/base-python-curriculum-questions#466]
I am still trying to get a better understanding of the getattr method and when to use it.  In this exercise, it is being called to get the value from the dictionary of hiding places IF the guess matches what is in the dictionary.  Why is self being used as the object parameter and not self.hidingplaces since we want to compare it against the keys in the dictionary.  

**Assignment**: http://learn.rmotr.com/python/base-python-track/advanced-oop/attribute-guessing

**User code**:
```python
class Location(object):
    def __init__(self, hidingplaces):
        self.hidingplaces = {}
        for key, value in hidingplaces.items():
            setattr(self,key,value)
         
            
    def search(self,guesses):
        prizes = []
        for guess in guesses:
            if hasattr(self,guess):
                prizes.append(getattr(self, guess))
        return prizes
    
```

**Comment by vchau76** [comment]
Bueller? Bueller? Bueller?

**Comment by jsymons** [comment]
Sorry, thought I had already responded to this. By storing the dictionary internally you're bypassing the purpose of the assignment. `self.hidingplaces` isn't supposed to exist. Thus we are trying to directly check if the instantiated object has those attributes, which is why we're paying self into setattr.
