### ISSUE TITLE
Index incrementing

### ISSUE THREAD

**Issue by code-kopilka** [rmotr-curriculum/base-python-curriculum-questions#472]
I have commented out 'index += 1' inside each 'if' statement because it is not working that way. Why incrementing indexes in each 'if' statement does not work? Why do I need to do it outside of those 'if' conditionals and do it where I am doing it now? Thank you in advance, Shavkat

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/count-in-even-odd-positions

**User code**:
```python
def count_in_position(a_string, a_char, position_type):
    
    total = 0
    index = 0
    
    for char in a_string:
        if char == a_char:
            if position_type == "even" and index % 2 ==0:
                total += 1
               # index += 1
            if position_type == "odd" and index % 2 == 1:
                total += 1
               # index += 1
        index += 1
    return total
```

**Comment by jsymons** [comment]
Because it wouldn't increment in the opposite type of number. If `position_type` is `even` then with the increment only in the if statement index will only be increased on even numbers.

Also you may want to look into the documentation for the `enumerate` function, it is designed for this kind of stuff so you don't have to manually handle the index.
