### ISSUE TITLE
'in' vs 'is' vs '=='

### ISSUE THREAD

**Issue by code-kopilka** [rmotr-curriculum/base-python-curriculum-questions#473]
Can you please better explain the difference between these with use cases and examples? Thank you

**Assignment**: http://learn.rmotr.com/python/base-python-track/week-1-quiz/count-in-even-odd-positions

**User code**:
```python
def count_in_position(a_string, a_char, position_type):
    
    total = 0
    index = 0
    
    for char in a_string:
        if char in a_char:
            if position_type == "even" and index % 2 ==0:
                total += 1
               # index += 1
            if position_type == "odd" and index % 2 == 1:
                total += 1
               # index += 1
        index += 1
    return total
```

**Comment by jsymons** [comment]
`in` is used to check of something *contains* for example `if 'a' in 'abcdefg'`

`is` checks if two things are the exact same object, not if they're equal. For example `1 is 1.0` is `False` while `1 == 1.0` is `True`. This is because `1` is an integer while `1.0` is a float, they are not the same object.

`==` checks if two things are equal.
