### ISSUE TITLE
Notes and examples

### ISSUE THREAD

**Issue by chinnappa-raju** [rmotr-curriculum/base-python-curriculum-questions#476]
Hi Santiago,
I dont see any notes or examples for this lesson (Hash tables) under base python curriculum in github. would you be uploading one soon?

**Assignment**: http://learn.rmotr.com/python/base-python-track/collections-part-2/hash-tables

**Comment by jwinf843** [comment]
Hash tables are a Computer Science topic that we highly encourage you to read more about if you're interested in them. For the sake of the beginner's python course, however, they're a bit complex and not entirely necessary to understand in order to properly implement data structures in python. Because of this, we don't currently have plans to integrate them, or other computer science topics into the beginner's python course.

**Comment by santiagobasulto** [comment]
@chinnappa-raju we haven't uploaded any notes except from the video. But this is probably the best tutorial online to learn more about it: https://www.hackerearth.com/practice/data-structures/hash-tables/basics-of-hash-tables/tutorial/
