### ISSUE TITLE
How to complete this task DRY, for indefinite number of parameters?

### ISSUE THREAD

**Issue by mikepeiman** [rmotr-curriculum/base-python-curriculum-questions#48]
So I got a solution, after checking other questions on Github. This is not DRY enough for me! I want to know how to do this with elegant code for an indefinite number of parameters. How do I do this with a loop based on number of parameters passed? Or how do I accomplish this with max()? I checked the Python documentation but I don't understand the language enough to know how to implement. Thanks!

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/greatest-parameter

**User code**:
```python
def greatest_parameter(a, b, c, d, e):
    highest = a
    if b > highest:
        highest = b
    if c > highest:
        highest = c
    if d > highest:
        highest = d
    if e > highest:
        highest = e

    return highest
```

**Comment by jsymons** [comment]
So first off you would need to change your function signature so that it accepted a *variable* number of arguments, this can be done as such:
```python
def greatest_parameter(*args):
```
Doing this causes the variable `args` to be a *tuple* containing all of the arguments. For example if we were to call `greatest_parameter(1, 2, 3)` then args would equal `(1, 2, 3)`

To then solve using a loop you would do something like:
```python
def greatest_parameter(*args):
    highest = None
    for i in args:
        if highest is None or i > highest:
            highest = i

    return highest
```
This iterates through the args and essentially does a comparison like you did in your code.
But `max` is a **much** cleaner solution:
```python
def greatest_parameter(*args):
    return max(args)
```
`max` takes an *iterable* (so like a tuple or list for example) and then returns the highest value from it.
You can read more about max [here](https://docs.python.org/3/library/functions.html#max)

**Comment by santiagobasulto** [comment]
@mikepeiman Can I close this one?
