### ISSUE TITLE
Intermediary list

### ISSUE THREAD

**Issue by mkrij** [rmotr-curriculum/base-python-curriculum-questions#51]
Hi, I was unable to pop from the dictionary, but rather created a new dictionary, and the code ended up working. However, in the interest of understanding the assignment (where it was clearly stated to remove values, and not create a new dictionary), can someone please explain why there is an intermediary list created in the solutions? What purpose does it serve? Thanks! 
-Mirza

**Assignment**: http://learn.rmotr.com/python/base-python-track/quiz-week-2/censor-your-dictionary

**User code**:
```python

```

**Comment by jsymons** [comment]
The list is being used to gather all the keys that need to be removed, after we have iterated over the dictionary we can then proceed to remove the items from it. We can't pop *during* the iteration over the dictionary because python will throw the following error if the dictionary changes size while iterating over it:
```
RuntimeError: dictionary changed size during iteration
```

**Comment by mkrij** [comment]
Thanks! I saw the error but was having trouble conceptualizing it. Your clarification has cleared all confusion!
