### ISSUE TITLE
This one is over my head. I would like to go through this with someone please.

### ISSUE THREAD

**Issue by propman1** [rmotr-curriculum/base-python-curriculum-questions#63]
I am not getting this

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/smooth-operator

**User code**:
```python
fav_number = 4815162342 
i_love_operators = True
my_spoon = "is too big"

# Use the shorthand to multiply fav_number by 2 and save the result back in fav_number
fav_number = fav_number * 2

# Use inequality operators to check if fav_number is less than or equal to 7
# Store the result in var1
var1 = fav_number <= 7

# Use the in keyword to check if the letter n is in my_spoon
# Store the result in var2
var2 = n in my_spoon

# Make a big operator expression that checks if var1 is True or if both
# i_love_operators and the opposite of var2 are True 
# Store the result in complicated. Don't forget to use parenthesis
complicated = var1 is true
```

**Comment by santiagobasulto** [comment]
hey @propman1! What you don't get? Errors or what the exercise is asking? I can quickly spot a few errors: `var is true` will probably fail because in Python  we use `True` with a capital `T`.

`n` in my spoon doesn't exist either. Just `n` refers to the variable `n`. What you probably want to do is `'n' in my_spoon`.

Please give us more details so we can help you.

**Comment by propman1** [comment]
Thank you Santiago. 
Let me try few more times.










-----Original Message-----

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.
