### ISSUE TITLE
How do I avoid 'Non' return when empty string is entered?

### ISSUE THREAD

**Issue by taeyu7720** [rmotr-curriculum/base-python-curriculum-questions#65]
I am getting 'None' instead of '' when I enter empty string.  How can I fix this?  Thanks!

**Assignment**: http://learn.rmotr.com/python/base-python-track/strings/max-character

**User code**:
```python
def max_char(a_string):
    char = ''
    for letter in a_string:
        char += max(a_string)
        return char
        if a_string == None:
            return ''
            
print(max_char('ooknmjv'))
```

**Comment by jsymons** [comment]
So if `a_string` has 0 length your for loop never executes because there's nothing to iterate over. So you need to check for that *before* your for loop.
Also as a side note, your return inside your for loop means that it will only ever do one iteration. When a return is encountered the function **immediately** returns, the rest of the function does not execute.
Example:
```
def return_example():
    print('I print.')
    return True
    print('I am never executed.')
```
When the `return` happens, nothing past it in the function is executed. This includes breaking loops.

**Comment by santiagobasulto** [comment]
@taeyu7720 can I close this one?

**Comment by taeyu7720** [comment]
Yes.  Thanks!

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.
