### ISSUE TITLE
Why the disparity

### ISSUE THREAD

**Issue by kufopi** [rmotr-curriculum/base-python-curriculum-questions#77]
A style of coding works for a question and does not for another

**Assignment**: http://learn.rmotr.com/python/base-python-track/operators/valid-passwords

**User code**:
```python
# this gives error
has_required_character_pwd_4 =  ('v'or'V'or'r'or'R'or'b'or'B' )  in password_4

## Has at least one symbol: $%#&, this doesn't
at_least_one_symbol_pwd_1 = ('$' or '%' or '#' or '&') in password_1
```

**Comment by jsymons** [comment]
The fact that the symbol version is working is actually a lucky coincidence. It's not actually doing what you're thinking it's doing. `('$' or '%' or '#' or '&')` is evaluating to `'$'` as it's the first **truthy** value in your or expression, it just happens that in the tests the only passwords that expect your statement to return true all have a `$` in them. Your required character statement `('v' or 'V' or 'r' or 'R' or 'b' or 'B') in password_4` is evaluating to essentially `'v' in password_4` again because the or statement spits out the first **truthy** value, in this case `'v'`, however *none* of the passwords contain a `'v'` and therefore they will all evaluate `False`.

Hope this clears things up, if you need more explanation on how the `or` statements are working let me know.

**Comment by santiagobasulto** [comment]
Closing this one for now. Reopen if necessary please.
