### ISSUE TITLE
Boolean subtype

### ISSUE THREAD

**Issue by ghost** [rmotr-curriculum/base-python-curriculum-questions#86]
I don't understand the the error in code at the boolean line

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/is-numeric

**User code**:
```python
def is_numeric(a_number):
    if isinstance (a_number, int) == True:
        return True
    elif isinstance (a_number, float) == True:
        return True
    elif isinstance (a_number, str) == True:
        return False
    elif isinstance (a_number, bool) == True:
        return False
```

**Comment by jsymons** [comment]
Ok, this is a python technicality. In Python a boolean is an instance of an integer (`True` and `False` are stored internally as `1` and `0` respectively). Because of this, the following code evaluates to `True`:
```python
a_boolean = True
isinstance(a_boolean, int) == True
```
There are two ways to work around this in your code, you can put your `isinstance` check against `bool` **before** you check against `int`, or you can use `type` instead of `isinstance` as type doesn't handle inheritance while `isinstance` does.
