### ISSUE TITLE
Variable assignments

### ISSUE THREAD

**Issue by codewithhope** [rmotr-curriculum/base-python-curriculum-questions#90]
If I make x = 5 and y = x, and I change the value of x later in the program, does the value of y change? Or does the value of y stay equal to 5 until you manually reassign it?

**Assignment**: http://learn.rmotr.com/python/base-python-track/getting-started/variables-and-assignments

**Comment by santiagobasulto** [comment]
Great question Daniel! Short answer, it doesn't change. Here's an example: https://repl.it/repls/ConfusedScientificLaboratory

The reason is that, when you do `y = x`, you're not assigning y to x, but **to the value referenced by `x`**:

![image](https://user-images.githubusercontent.com/872296/39663107-659967ee-5043-11e8-9e19-25dd88887073.png)

This WILL change when we start using mutable objects (like lists in week 2). This might be a little bit confusing, but here it is: https://repl.it/repls/HappyShowyDehardwarization
