### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by deboragaleano** [rmotr-curriculum/base-python-curriculum-questions#92]
there's something wrong in my code and i can't see what it is (I think it's because I didn't quite understand why we need to create a def for repeating strings). 

**Assignment**: http://learn.rmotr.com/python/base-python-track/intro-to-control-flow/knock-3-times

**User code**:
```python
def knock_three_times(counter):
    counter = 1
    while counter < 4:
        print("Knock Knock")
        counter += 1


```

**Comment by jsymons** [comment]
First let's look at the error your code is generating:
```
tests.py:29: in test_knock_three_times
    knock_three_times()
E   TypeError: knock_three_times() missing 1 required positional argument: 'counter'
```
So the error says we're missing 1 required positional argument, 'counter.
Let's look at our function signature:
```python
def knock_three_times(counter):
```
So this states that our function expects to be called something like this: `knock_three_times(my_counter_variable)` However, if we look at how the *test* calls the function:
```python
def test_knock_three_times():
    with CaptureOutput() as output:
        knock_three_times()
```
See how there is nothing being passed to the function? `knock_three_times()` nothing between the parentheses means no parameters being passed. Because of this mismatch between the function signature and the way we're calling the method Python is giving us the error you're receiving. To fix this we need to change the **function signature**. Our function does not require having the `counter` passed into it since we've already defined it inside the function with:
```python
counter = 1
```
So if we change our signature to:
```python
def knock_three_times():
```
That should clear up the error.

Hope that clears things up. If you have further questions on this, let me know.
